#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: appmgr
#   Version: 1.0
#
#   Usage:
#
#   Description:
#		Appmenu, App switcher, etc.
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1
REQUIRE_CMD "rofi" || exit 1

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Invoke common app management programs."
SCRIPT_USAGE="[FLAG]"

# Examples
EXAMPLE "--menu"

# Flags
FLAG "--menu" "" "GUI Application Menu"
FLAG "--switcher" "" "Switch between running GUI apps"

##############################################
# MAIN LOGIC

function appmgr.menu() {
	SILENTRUN rofi -show drun -scroll-method 1 -show-icons -columns 2 -disable-history -sorting-method 'fzf'
}

function appmgr.switcher() {
	SILENTRUN rofi -show window -window-icon -window-format "{c}    {t}"
}

# If no arguments are give, just show help prompt.
[[ $# -eq 0 ]] && HELP && exit 0

# Iterate over all arguments and evaluate them
while [[ $# -gt 0 ]]; do

	case "$(LOWERCASE "${1}")" in

	-m | --menu)
		shift
		appmgr.menu
		exit $?
		;;

	-s | --switcher)
		shift
		appmgr.switcher
		exit $?
		;;

	\? | -h | --help)
		shift
		HELP
		exit 0
		;;

	*)
		INVALID_CMD "${1}"
		exit 1
		;;

	esac

done
