#!/bin/bash

#  ██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗
#  ██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║
#  ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║
#  ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║
#  ██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗
#  ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Roll one or more random numbers and format the output"
SCRIPT_USAGE="[FLAGS] [NUMBERS] ..."
SCRIPT_EXAMPLE="50 100 500"

# Examples
EXAMPLE "50 100" "Roll dice from 1-50 and 1-100"
EXAMPLE "-r 50" "Don't print 'd#:' in front of result"

# Flags
FLAG "-r, --raw" "" "Print only the numbers"
FLAG "-o, --one-line" "" "Print all the numbers on one line"

##############################################
# MAIN LOGIC

RAW=1
ONELINE=1
NUMBERS=()
RESULTS=()

[[ $# -eq 0 ]] && {
	HELP
	exit 0
}

while [[ $# -gt 0 ]]; do
	case "$(LOWERCASE "${1}")" in

	-r | --raw)
		shift
		RAW=0
		;;
	-o | --one-line)
		shift
		ONELINE=0
		;;
	\? | -h | --help)
		shift
		HELP
		exit 0
		;;
	*)
		IS_NUMBER "${1}" || { shift && continue; }
		(($1 > 0)) && NUMBERS+=("$1") && RESULTS+=("$((RANDOM % $1 + 1))")
		shift
		;;

	esac
done

# if the '--oneline' flag is used, print all results on a new line.
[[ $ONELINE -eq 0 ]] &&
	{ for result in "${RESULTS[@]}"; do NPRINT "${result} "; done; } && PRINT && exit 0

# print the results on new lines; default format is 'd0: 0'; '--raw' prints format as '0'.
for ((i = 0; i < ${#RESULTS[@]}; i++)); do

	[[ $RAW -ne 1 ]] && PRINT "${RESULTS[i]}"
	[[ $RAW -eq 1 ]] && PRINT "d${NUMBERS[i]}: ${RESULTS[i]}"

done
