#!/usr/bin/env bash

##############################################
#	Author: RMCJ <rmichael1001@gmail.com>
#	Project: emojictl
#	Version: 1.0
#
#	Usage: emojictl [command] [args]
#
#	Description:
#		Install/uninstall Noto Color Emoji on Linux
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1
REQUIRE_CMD "wget" "unzip" "fc-cache" || exit 1

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Manage system emojis"
SCRIPT_USAGE="[FLAG]"

# Flags
FLAG "-i, --install" "" "Install emojis"
FLAG "-u, --uninstall" "" "Uninstall emojis"

##############################################
# MAIN LOGIC

# Noto Emoji package link
EMOJIPKG="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"

CONFLINK="https://raw.githubusercontent.com/rmj1001/HeckerShell/main/files/.config/fontconfig/conf.d"

# Fontconfig file links
FONTCONFIGS=(
	"${CONFLINK}/01-dejavu.conf"
	"${CONFLINK}/02-mozilla.conf"
	"${CONFLINK}/03-emoji.conf"
)

# Directories
CONFDIR=$HOME/.config/fontconfig/conf.d
NOTOPKG="$HOME/Downloads/$(basename ${EMOJIPKG})"
TEMP=$HOME/Downloads/temp
FONTS=$HOME/.fonts
FILE=${FONTS}/NotoColorEmoji.ttf

# cmd
cmd=""

function emojictl.prepare() {
	# Make the config directory and move to it
	[[ ! -d "${CONFDIR}" ]] && mkdir -p "${CONFDIR}"
	[[ ! -d "${FONTS}" ]] && mkdir -p "${FONTS}"
	[[ ! -d "${TEMP}" ]] || mkdir "${TEMP}"
	[[ -d "${TEMP}" ]] && rm -rf "${TEMP:?}/*"
	[[ -f "${FILE}" ]] && rm -rf "${FILE}"
	[[ -f "${NOTOPKG}" ]] && rm -f "${NOTOPKG}"
}

function emojictl.emojis.install() {
	clear

	# Make the config directory and move to it
	emojictl.prepare
	cd "$CONFDIR" || return 1

	# Download the fontconfig files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename "$file")
		rm -f "$name"
		wget "$file"
	done

	# Download noto emoji font
	cd "$TEMP" || return 1
	wget $EMOJIPKG

	# Install emojis
	unzip NotoColorEmoji-unhinted.zip
	mv NotoColorEmoji.ttf "$FONTS"
	fc-cache -fv
	rm -rf "$TEMP"

	# Post
	clear
	PRINT
	PRINT "Install finished."
	PRINT
	PAUSE
	clear
}

function emojictl.emojis.uninstall() {
	clear
	emojictl.prepare

	# Remove the font file
	rm -f "${FONTS}"/NotoColorEmoji.ttf

	# Remove the config files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename "${file}")
		rm -f "${CONFDIR}/${name}"
	done

	# Reload the font cache
	fc-cache -fv

	# Post
	clear
	PRINT
	PRINT "Uninstall finished."
	PRINT
	PAUSE
	clear
}

# If no arguments are give, just show help prompt.
[[ $# -eq 0 ]] && {
	HELP
	exit 0
}

# Iterate over all arguments and evaluate them
while [[ $# -gt 0 ]]; do

	case "$(LOWERCASE "${1}")" in

	-i | --install)
		shift
		emojictl.emojis.install
		exit 0
		;;
	-u | --uninstall)
		shift
		emojictl.emojis.uninstall
		exit 0
		;;
	\? | -h | --help)
		shift
		HELP
		exit 0
		;;
	*)
		shift
		INVALID_CMD "${1}"
		exit 1
		;;

	esac

done
