#!/usr/bin/env bash

##############################################
#	Author: RMCJ <rmichael1001@gmail.com>
#	Project: mansplain
#	Version: 1.0
#
#	Usage: mansplain [command] [args]
#
#	Description:
#		Use dmenu to view manpages in PDF format
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1
REQUIRE_CMD "rofi" "zathura" "ps2pdf" || exit 1

##############################################
# MAIN LOGIC

function menu() {
	rofi -dmenu -columns 3 -disable-history -p "Manpage" -mesg "Pick the manpage you want to view in Zathura."
}

name="$(man -k . | awk '{print $1}' | menu)"

[[ -z "${name}" ]] && FAIL "You didn't specify a name."

man -t "${name}" | ps2pdf - "${name}.pdf"

[[ -f "${name}.pdf" ]] || FAIL "I couldn't generate the PDF for that manpage..."

zathura "${name}.pdf"
rm -rf "${name}.pdf"
