#!/usr/bin/env bash

##############################################
#	Author: RMCJ <rmichael1001@gmail.com>
#	Project: mansplain
#	Version: 1.0
#
#	Usage: mansplain [command] [args]
#
#	Description:
#		Use dmenu to view manpages in PDF format
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1

##############################################
# MAIN LOGIC
##############################################

ZATHURA=0

[ "$1" = "-z" ] && {
  REQUIRE_CMD "zathura" || exit 1
  ZATHURA=1
}

rofi_man() {
    REQUIRE_CMD "rofi" || exit 1

    function menu() {
	    rofi -dmenu -columns 3 -disable-history -p "Manpage" -mesg "Pick the manpage you want to view in Zathura."
    }

    name="$(man -k . | awk '{print $1}' | menu)"

    [[ -z "${name}" ]] && FAIL "You didn't specify a name."

    man -t "${name}" | ps2pdf - "${name}.pdf"

    [[ -f "${name}.pdf" ]] || FAIL "I couldn't generate the PDF for that manpage..."

    zathura "${name}.pdf"
    rm -rf "${name}.pdf"

    exit 0
}

fzf_man() {
  REQUIRE_CMD "fzf" || exit 1

  [ $ZATHURA -eq 1 ] && man -k . | awk '{print $1}' | fzf | xargs -r man -Tpdf | zathura

  man -k . | awk '{print $1}' | fzf | xargs -r man

  exit 0
}

for flag in $#; do
  case "$flag" in
    -z|--zathura)
      REQUIRE_CMD "zathura" || exit 1
      ZATHURA=1
      ;;
  esac
done

for flag in $#; do
  case "$flag" in
    -r | --rofi)
      rofi_man
      ;;
    -f | --fzf)
      fzf_man
      ;;
    *)
      fzf_man
      ;;
  esac
done
