#!/usr/bin/env bash

##############################################
# Author(s): RMCJ <rmichael1001@gmail.com>
# Project: minecraftctl
# Version: 1.0
#
# Usage: minecraftctl [command] [args]
#
# Description:
#	Manage minecraft installations
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1
REQUIRE_CMD "wget" "tar" "ar" || exit 1

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Manage your minecraft installation"
SCRIPT_USAGE="[FLAGS] [ARGS?] ..."

# Examples
EXAMPLE "--install"

# Flags
FLAG "-i, --install" "" "Install Minecraft"
FLAG "-r, --remove" "" "Uninstall Minecraft"
FLAG "-u, --update" "" "Update Minecraft"

##############################################
# MAIN LOGIC

desktopEntry="/usr/share/applications/minecraft-launcher.desktop"
downloadLink="https://launcher.mojang.com/download/Minecraft.deb"
binary="/usr/bin/minecraft-launcher"
desktopEntry="/usr/share/applications/minecraft.desktop"

function minecraftctl.install() {
	# Clear Screen
	clear

	# Variables
	local link="${downloadLink}"
	local dentry="${desktopEntry}"

	# Download
	cd "${HOME}/Downloads" || return 1

	# If deb file exists, delete and download new one, otherwise just download
	[[ -f "Minecraft.deb" ]] && clear && rm -f ./Minecraft.deb
	wget "${link}"

	PRINT "Installing Minecraft..."

	# Install the deb file
	sudo ar xvf Minecraft.deb
	sudo tar xvf data.tar.xz -C /
	sudo rm control.tar.gz data.tar.xz debian-binary

	# Desktop Entry
	entryText="Exec=env JAVA_HOME=/usr/lib64/openjdk-8 ${binary}"

	# Create the desktop entry
	PRINT "${entryText}" | sudo tee -a "${dentry}"
	PRINT "Icon=/usr/share/icons/hicolor/symbolic/apps/minecraft-launcher.svg" | sudo tee -a "${dentry}"
	PAUSE

	# Confirmation
	clear
	PRINT "Installation finished."
	PRINT
	PAUSE
	clear
}

function minecraftctl.remove() {
	# Clear screen
	clear

	local launcherExisted=0 # Tracks existence of launcher directories
	local filesExisted=0    # Tracks existence of any files from minecraftctl.

	# Remove launcher files
	[[ -e "${binary}" ]] && launcherExisted=1 && sudo rm -rf ${binary} && sleep 1.5
	[[ -e "${desktopEntry}" ]] && launcherExisted=1 && sudo rm -rf ${desktopEntry} &&
		PRINT "Removed desktop entry." && sleep 1.5

	[[ ${launcherExisted} -eq 1 ]] && filesExisted=1 && PRINT "Removed launcher."
	[[ ${filesExisted} -eq 1 ]] && PRINT "Uninstallation finished."
	[[ ${filesExisted} -ne 1 ]] && PRINT "Minecraft is not installed."

	# Confirmation
	PAUSE
	clear
}

[[ $# -eq 0 ]] && {
	HELP
	exit 0
}

case "$(LOWERCASE "${1}")" in
-i | --install)
	minecraftctl.install
	;;
-r | --remove)
	minecraftctl.remove
	;;
-u | --update)
	minecraftctl.remove && minecraftctl.install
	;;
\? | -h | --help)
	HELP
	;;
*)
	INVALID_CMD "${1}"
	exit 1
	;;
esac
