#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: pactools
#   Version: 1.0
#
#   Usage: [flags]
#
#   Description:
#	Browse installed pacman packages
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT || exit 1

####################################

function _browse() {
	trap 'exit 0' SIGINT SIGHUP

	REQUIRE_CMD "pacman" || return 1

	pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

function _refresh_mirrors() {
	REQUIRE_CMD "reflector" || return 1

	sudo reflector --latest 100 --protocol https --sort rate --verbose --save /etc/pacman.d/mirrorlist
}

function _list_orphans() {
	pacman -Qtdq
}

function _remove_orphans() {
	pacman -Qtdq | sudo pacman -Rns -
}

function _help() {
	PRINT "$(SCRIPTNAME) - Various pacman tools"
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) <flag> <args?>"
	PRINT "Example:\t$(SCRIPTNAME) --help"
	PRINT
	{
		PRINT "-------------|------|---------------------"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------"
		PRINT "||"
		PRINT "-b, --browse||Browse pacman packages"
		PRINT "-u, --update-mirrors||Update mirrors to fastest available"
		PRINT "-l, --list-orphans||List orphaned packages (former dependencies)"
		PRINT "-r, --remove-orphans||Remove orphaned packages"
		PRINT "||"
		PRINT "-h, --help|n/a|Show this prompt"
	} | column -t -s'|'
}

case "$(LOWERCASE "$1")" in

-b | --browse) _browse ;;

-u | --update-mirrors) _refresh_mirrors ;;

-l | --list-orphans) _list_orphans ;;

-r | --remove-orphans) _remove_orphans ;;

\? | -h | --help) _help ;;

*)
	[[ -z "$1" ]] && _help && exit 0
	PRINT "Invalid command '$1'!" && exit 1
	;;

esac
