#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project:
#   Version: 1.0
#
#   Usage: passgen [NUMBER OF CHARACTERS? (default 16)]
#
#   Description:
#       This generates a random password
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessing flags
DISABLE_ROOT || exit 1
REQUIRE_CMD "tr" "fold" "head" || exit 1

####################################

chars="16"
[[ -n "${1}" ]] && chars="${1}"

tr -cd '[:alnum:]' </dev/urandom | fold -w"${chars}" | head -n 1
