#!/bin/bash

#  ██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗
#  ██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║
#  ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║
#  ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║
#  ██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗
#  ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1

##############################################
# HELP MENU BUILDER

VERSION "1.5"
DESCRIPTION "Manage the shell configuration"
USAGE "[FLAG] [directory]? ..."

# Flags
FLAG "reload" "" "Reload shell configs"
FLAG "fresh-screen" "" "Clear screen and print MOTD"
FLAG "lines" "" "Print a line across the screen"
FLAG "motd" "" "Print or manage the MOTD. See '${0##*/} motd --help'."
FLAG "" "" ""
FLAG "update" "" "Update this shell"
FLAG "clean-update" "" "Uninstall & Re-install this shell"
FLAG "uninstall" "Uninstall this shell"

##############################################
# MAIN LOGIC

# HeckerShell urls
export HECKERSHELL_SITE_HTTPS="https://github.com/rmj1001/HeckerShell.git"
export HECKERSHELL_SITE_SSH="git@github.com:rmj1001/HeckerShell.git"
export HECKERSHELL_SITE="${HECKERSHELL_SITE_HTTPS}"

# HeckerShell directories
export HECKERSHELL_DOWN_DIR="${HOME}/.local/share"
export HECKERSHELL_DIR="${HECKERSHELL_DOWN_DIR}/HeckerShell"
export HECKERSHELL="${HECKERSHELL_DIR}/files"

# OG Paths
export SYM_ZSHRC="${HECKERSHELL}/.zshrc"
export SYM_BASHRC="${HECKERSHELL}/.bashrc"
export SYM_SHELLFILES="${HECKERSHELL}/.shellfiles"
export SYM_SCRIPTS="${HECKERSHELL}/Scripts"

# Paths
export ZSHRC="${HOME}/.zshrc"
export BASHRC="${HOME}/.bashrc"
export SHELLFILES="${HOME}/.shellfiles"
export SCRIPTS="${HOME}/Scripts"

### Reload shell files and present fresh screen.
# Usage: shell reload
shell_reload() {
  exec "$(basename "${SHELL}")"
}

### Write lines to terminal (full width of screen)
# Usage: shell lines
shell_lines() {
  printf %"$COLUMNS"s | tr " " "-"
}

# Print custom MOTD to terminal
# Usage: shell motd
shell_motd() {
  PRINT
  PRINT "██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗     "
  PRINT "██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║     "
  PRINT "███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║     "
  PRINT "██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║     "
  PRINT "██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗"
  PRINT "╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝"
  PRINT "                                                                                        "
}

### Clear screen and print motd
# Usage: shell freshscreen
shell_freshscreen() {
  clear
  shell_motd
  [ "${SHELL}" = "/bin/zsh" ] && PRINT ""
}

shell_install() {
  bash <(wget -qO- https://raw.githubusercontent.com/rmj1001/HeckerShell/main/auto/install.sh)
}

shell_uninstall() {
  bash <(wget -qO- https://raw.githubusercontent.com/rmj1001/HeckerShell/main/auto/uninstall.sh)
}

shell_update() {
  bash <(wget -qO- https://raw.githubusercontent.com/rmj1001/HeckerShell/main/auto/update.sh)
  shell_reload
}

shell_cleanupdate() {
  shell_uninstall
  shell_install
  shell_reload
}

[ $# -eq 0 ] && HELP && exit 0

case "$(LOWERCASE "${1}")" in
help)
  HELP
  ;;
reload)
  shell_reload
  ;;
fresh-screen)
  shell_freshscreen
  ;;
lines)
  shell_lines
  ;;
motd)
  shift
  shell_motd
  ;;
update)
  shift
  shell_update
  ;;
clean-update)
  shift
  shell_cleanupdate
  ;;
uninstall)
  shift
  shell_uninstall
  ;;
*)
  HELP
  ;;
esac
