#!/usr/bin/env bash

##############################################
#	Author: RMCJ <rmichael1001@gmail.com>
#	Project: trash
#	Version: 1.0
#
#	Usage: trash [command] [args]
#
#	Description:
#		This utility manages your trash bin.
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT || exit 1

####################################

declare -- TRASHINFO
declare -- FILENAME
declare -- FILEINFO
declare -- DELPATH
declare -- DELDATE
declare -- FILEPATH
declare -- FILEINFO
declare -- RESTOREPATH

TRASHDIRS=$HOME/.local/share/Trash
TRASHINFO=$TRASHDIRS/info
[ -z "$TRASH" ] && TRASH=$TRASHDIRS/files

function trash.file.check() {
  if [ -n "$1" ]; then
    FILE="$1"
  else
    PRINT "You must specify a FILE." && exit 1
  fi
}

function trash.getPath() {
  confFile="${1}"
  PRINT "$(grep -m 1 Path= "${confFile}" | sed 's|Path=||')"
}

function trash.getDate() {
  confFile="${1}"
  PRINT "$(grep -m 1 DeletionDate= "${confFile}" | sed 's|DeletionDate=||')"
}

function trash.files.add() {
  trash.file.check "$1"
  if [ -e "${FILE}" ]; then
    FILENAME="$(basename "${FILE}")"
    DELPATH=$(readlink -f "${FILE}")
    DELDATE=$(date +"%Y-%m-%dT%H:%M:%S")

    PRINT "[Trash Info]" >"${TRASHINFO}/${FILENAME}.trashinfo"
    PRINT "Path=${DELPATH}" >>"${TRASHINFO}/${FILENAME}.trashinfo"
    PRINT "DeletionDate=${DELDATE}" >>"${TRASHINFO}/${FILENAME}.trashinfo"
    mv "${FILE}" "${TRASH}"

    PRINT "Moved ${FILE} to the trash!"
    exit 0
  else
    PRINT "File '${FILE}' doesn't exist!" && exit 1
  fi
}

function trash.files.restore() {
  trash.file.check "$1"

  FILEPATH="${TRASH}/${FILE}"
  FILEINFO="${TRASHINFO}/${FILE}.trashinfo"

  if [ -f "${FILEINFO}" ] && [ -e "${FILEPATH}" ]; then
    RESTOREPATH="$(trash.getPath "${FILEINFO}")"

    mv "${FILEPATH}" "${RESTOREPATH}"
    rm -f "${FILEINFO}"

    PRINT "Restored ${FILE} to ${RESTOREPATH}!"
    exit 0
  else
    PRINT "File ${FILE} is not in the trash!" && exit 1
  fi
}

function trash.files.empty() {
  cd "${TRASH}" && SILENTRUN rm -rf ./*
  cd "${TRASHINFO}" && SILENTRUN rm -rf ./*

  PRINT "Trash emptied!"
}

function trash.files.information() {
  trash.file.check "$1"

  FILEINFO=$TRASHINFO/"${FILE}.trashinfo"

  if [ -e "${FILEINFO}" ]; then
    cat "${FILEINFO}"
    exit 0
  else
    PRINT "File does not have metadata / doesn't exist!" && exit 1
  fi
}

function trash.help() {
  PRINT "$(SCRIPTNAME) - Manage your trash bin"
  PRINT
  PRINT "Usage:\t\t$(SCRIPTNAME) [FLAGS] [ARGS?] ..."
  PRINT "Example:\t$(SCRIPTNAME) --help"
  PRINT
  {
    PRINT "-------------|------|---------------------"
    PRINT "Flag|Args|Description"
    PRINT "-------------|------|---------------------"
    PRINT "||"
    PRINT "-a, --add|<file>|Add a file to the trash"
    PRINT "-r, --restore|<file>|Restore a file from the trash"
    PRINT "-e, --empty||Empty the trash bin"
    PRINT "-i, --info|<file>|Get a trashed file's metadata"
    PRINT "-l, --list||List the contents of the trash bin"
    PRINT "||"
    PRINT "-h, --help|n/a|Show this prompt"
  } | column -t -s'|'
}

cmd="$(LOWERCASE "${1}")"

case "${cmd}" in
-a | --add)
  trash.files.add "${2}"
  ;;
-r | --restore)
  trash.files.restore "${2}"
  ;;
-e | --empty)
  trash.files.empty
  ;;
-l | --list)
  ls --color=auto -AlvhF --group-directories-first "${TRASH}"
  exit 0
  ;;
-i | --info)
  trash.files.information "${2}"
  ;;
\? | h | help)
  trash.help
  ;;
*)
  [ -z "${cmd}" ] && trash.help || { INVALID_CMD "${1}" && exit 1; }
  ;;
esac
