#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: update
#   Version: 1.0
#
#   Usage: update
#
#   Description: Update all software on your
#	linux PC.
##############################################

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1
TITLE "Updater"

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Update system applications in batches."
SCRIPT_USAGE="[FLAGS]"

# Examples
EXAMPLE "-a -l" "Update all software & create logs"

# Flags
FLAG "-a, --all" "" "Update all software"
FLAG "-l, --log" "" "Create logs for updates"
FLAG "-c, --clear" "" "Clear the screen after each update"
FLAG "-n, --notify" "" "Send system notifications after each update"

##############################################
# MAIN LOGIC

all=0
log=0
clearscr=0
notify=0

function LOG() {
	local folder

	folder="${HOME}/.local/share/com.github.rmj1001.HeckerShell.updater/logs"
	logfile="${folder}/$(date -u +"%Y-%m-%dT%H").log"

	mkdir -p "${folder}"
	touch "${logfile}"
	"${@}" 2>&1 | tee "${logfile}"
}

function CLEAR() {
	[[ $clearscr -eq 1 ]] && clear && return 0
	PRINT
}

function UPDATE() {
	req="${1}" cmd="${2}"
	shift
	shift

	# If cmd does not exist, return error.
	CMD_EXISTS "${req}" || return 1

	function update.logic() {
		PRINT "Updating ${req}..."
		PRINT

		[[ $log -eq 0 ]] && eval "${cmd}"
		[[ $log -eq 1 ]] && LOG eval "${cmd}"

		[[ $notify -eq 1 ]] && CMD_EXISTS "notify-send" &&
			notify-send -i info -t 250 "Updated '${req}'."

		PRINT "Updated '${req}'."

		PAUSE

		CLEAR
	}

	[[ $all -eq 1 ]] && {
		update.logic
		return 0
	}

	PROMPT_YES "Update \"${req}\"" && {
		_logic
		return 0
	}

	PRINT "Skipped updating \"${req}\"."
	PAUSE
	CLEAR
	return 1
}

while [[ $# -gt 0 ]]; do

	case "$(LOWERCASE ${1})" in
	-a | --all)
		shift
		all=1
		continue
		;;
	-l | --log)
		shift
		log=1
		continue
		;;
	-c | --clear)
		shift
		clearscr=1
		continue
		;;
	-n | --notify)
		shift
		notify=1
		continue
		;;
	\? | -h | --help)
		shift
		HELP
		;;
	esac

done

CLEAR

UPDATE "flatpak" "flatpak update --assumeyes"
UPDATE "snap" "sudo snap refresh"
UPDATE "brew" "brew upgrade"
UPDATE "apt" "sudo apt update && sudo apt upgrade"
UPDATE "dnf" "sudo dnf update --assumeyes"
UPDATE "rpm-ostree" "rpm-ostree upgrade --assumeyes"
UPDATE "pacman" "sudo pacman -Syu --noconfirm"
UPDATE "yay" "yay -Sua --noconfirm"
UPDATE "paru" "paru -Sua --noconfirm"

CLEAR

PRINT "Finished updates!"
