#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: update
#   Version: 1.0
#
#   Usage: update
#
#   Description: Update all software on your
#	linux PC.
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT || exit 1
TITLE "Updater"

####################################

all=0
log=0
clearscr=0
notify=0

function _help() {
	PRINT "$(SCRIPTNAME) - Update system applications in batches."
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) [FLAGS] [ARGS?] ..."
	PRINT "Example:\t$(SCRIPTNAME) --help"
	PRINT
	{
		PRINT "-------------|------|---------------------"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------"
		PRINT "||"
		PRINT "-a, --all||Update all software"
		PRINT "-l, --log||Create logs for updates"
		PRINT "-c, --clear||Clear the screen after each update"
		PRINT "-n, --notify||Send notifications for each update"
		PRINT "||"
		PRINT "-h, --help|n/a|Show this prompt"
	} | column -t -s'|'
}

function LOG() {
	local folder

	folder="${HOME}/.local/share/com.github.rmj1001.HeckerShell.updater/logs"
	logfile="${folder}/$(date -u +"%Y-%m-%dT%H").log"

	mkdir -p "${folder}"
	touch "${logfile}"
	"${@}" 2>&1 | tee "${logfile}"
}

function CLEAR() {
	[[ $clearscr -eq 1 ]] && clear && return 0
	PRINT
}

function UPDATE() {
	req="${1}" cmd="${2}"
	shift
	shift

	# If cmd does not exist, return error.
	CMD_EXISTS "${req}" || return 1

	function _logic() {
		PRINT "Updating ${req}..."
		PRINT

		[[ $log -eq 0 ]] && eval "${cmd}"
		[[ $log -eq 1 ]] && LOG eval "${cmd}"

		[[ $notify -eq 1 ]] && CMD_EXISTS "notify-send" &&
			notify-send -i info -t 250 "Updated '${req}'."

		PRINT "Updated '${req}'."

		PAUSE

		CLEAR
	}

	[[ $all -eq 1 ]] && {
		_logic
		return 0
	}

	PROMPT_YES "Update \"${req}\"" && {
		_logic
		return 0
	}

	PRINT "Skipped updating \"${req}\"."
	PAUSE
	CLEAR
	return 1
}

while [[ $# -gt 0 ]]; do

	case "$(LOWERCASE ${1})" in
	-a | --all)
		shift
		all=1
		continue
		;;
	-l | --log)
		shift
		log=1
		continue
		;;
	-c | --clear)
		shift
		clearscr=1
		continue
		;;
	-n | --notify)
		shift
		notify=1
		continue
		;;
	\? | -h | --help)
		shift
		_help
		exit 0
		;;
	esac

done

CLEAR

UPDATE "flatpak" "flatpak update --assumeyes"
UPDATE "snap" "sudo snap refresh"
UPDATE "brew" "brew upgrade"
UPDATE "apt" "sudo apt update && sudo apt upgrade"
UPDATE "dnf" "sudo dnf update --assumeyes"
UPDATE "rpm-ostree" "rpm-ostree upgrade --assumeyes"
UPDATE "pacman" "sudo pacman -Syu --noconfirm"
UPDATE "yay" "yay -Sua --noconfirm"
UPDATE "paru" "paru -Sua --noconfirm"

CLEAR

PRINT "Finished updates!"
