#!/usr/bin/env bash

#  ██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗
#  ██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║
#  ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║
#  ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║
#  ██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗
#  ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1

##############################################
# HELP MENU BUILDER

SCRIPT_VERSION="1.5"
SCRIPT_DESCRIPTION="Manage volume via CLI."
SCRIPT_USAGE="[FLAGS] [ARGS?] ..."
SCRIPT_EXAMPLE="--mute"

# Examples
EXAMPLE "--mute"

# Flags
FLAG "-u, --up" "%" "Turn up volume %"
FLAG "-d, --down" "%" "Turn down volume %"
FLAG "-m, --mute" "" "Turn off volume"
FLAG "-v, --view" "" "Print current volume %"

##############################################
# MAIN LOGIC

function volume.up() {
	percent=${1:-15}
	SILENTRUN amixer sset Master "${percent}%+"
}

function volume.down() {
	percent=${1:-15}
	SILENTRUN amixer sset Master "${percent}%-"
}

function volume.mute() {
	SILENTRUN amixer sset Master toggle
}

function volume.view() {
	local volume

	volume="$(amixer sget Master | grep 'Front Left' | grep '%' | sed -e 's|.* Playback [0-9]* ||g' -e 's|\[on\]||g' -re 's|[^0-9]||g')%"

	PRINT "${volume}"
}

# If no arguments are give, just show help prompt.
[[ $# -eq 0 ]] && {
	HELP
	exit 0
}

# Iterate over all arguments and evaluate them
while [[ $# -gt 0 ]]; do

	case "$(LOWERCASE "${1}")" in

	-u | --up)
		shift
		volume.up "${1}"
		shift
		;;

	-d | --down)
		shift
		volume.down "${1}"
		shift
		;;

	-m | --mute)
		shift
		volume.mute
		;;

	-v | --view)
		shift
		volume.view
		;;

	\? | -h | --help)
		shift
		HELP
		exit 0
		;;

	*)
		INVALID_CMD "${1}"
		exit 1
		;;

	esac

done
