#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: golive
#	Version: 1.0
#
#	Usage: golive [command] [args]
#
#	Description:
#		Force pulseaudio to use settings that allows
#		linux users to share audio via Discord's
#		golive feature
##############################################

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Help Menu #
#############

api.script.author "Nidia Achrys"
api.script.setVersion "1.0"

# Description/usage/examples
api.script.description "Enable/disable sound sharing for discord with Pulseaudio"
api.script.usage "[command]"
api.script.example "start"

# CLI Commands
api.script.option "s" "start" "Start the sound sharing"

#############
# Core Code #
#############

api.required.command "pactl"

golive.setup ()
{
	pactl list short modules | grep -q 'Virtual_Sink' && return

	if [ -z "$MIC_SOURCE" ]; then
		first_source=$(pactl list short sources | head -1 | awk '{print $1;}') # e.g. 0
		pactl list short sources
		read -p ">> Source (input) number to use [$first_source]: " user_source
		[ -z "$user_source" ] && user_source=$first_source
		MIC_SOURCE=$user_source
		api.std.printLn 
		first_sink=$(pactl list short sinks | head -1 | awk '{print $1;}') # e.g. 1
		pactl list short sinks
		read -p ">> Sink (output) number to use [$first_sink]: " user_sink
		[ -z "$user_sink" ] && user_sink=$first_sink
		OUTPUT_SINK=$user_sink
		api.std.printLn 
	fi

	pactl load-module module-null-sink sink_name=Virtual_Output sink_properties=device.description=Virtual_Output > /dev/null
	pactl load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink > /dev/null
	MIX_SOURCE=$(pactl list short sources | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 14

	pactl load-module module-loopback latency_msec=1 source=$MIC_SOURCE sink=Virtual_Output > /dev/null
	pactl load-module module-loopback latency_msec=1 source=$MIX_SOURCE sink=Virtual_Output > /dev/null
	MIX_LOOPBACK=$(pactl load-module module-loopback latency_msec=1 source=$MIX_SOURCE sink=$OUTPUT_SINK)
}

golive.cleanup ()
{
	virtual_sink=$(pactl list short modules | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 30
	[ -z "$virtual_sink" ] && return
	read -p '>> Press enter to unload PulseAudio modules for the virtual mix...'

	[ ! -z "$MIX_LOOPBACK" ] && pactl unload-module $MIX_LOOPBACK || pactl unload-module module-loopback
	pactl list short modules | grep -E 'Virtual_(Sink|Output)' | awk '{print $1;}' | xargs -L1 pactl unload-module
}

golive.run ()
{
	golive.setup
	api.std.printLn ">> Your virtual mix is currently active! Feel free to open e.g. 'pavucontrol' now."
	api.std.printLn 
	api.std.printLn ">> For software that should have their audio included in the mix, move them"
	api.std.printLn "   to the 'Virtual_Sink' under the 'Playback' tab."
	api.std.printLn ">> For software that should capture the mixed audio, head to the 'Recording'"
	api.std.printLn "   tab and make the software use 'Monitor of Virtual_Output' as their input."
	api.std.printLn 
	golive.cleanup
}

cmd=`api.string.toLowerCase "${1}"`

case "${cmd}" in
	s | start )
		golive.run
		;;
	\? | h | help )
		api.script.help
		;;
	v | version )
		api.script.version
		;;
	* )
		if [ -z "${cmd}" ];
		then
			api.script.help
		else
			api.errors.invalidCommand "${cmd}"
		fi
		;;
esac
