#!/bin/bash

#  ██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗
#  ██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║
#  ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║
#  ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║
#  ██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗
#  ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#

##############################################
# PRE-PROCESSING

[[ -f "./00-api.sh" ]] || source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh
source ./00-api.sh

DISABLE_ROOT || exit 1

##############################################
# HELP MENU BUILDER

VERSION "1.5"
DESCRIPTION "Configure which files in \$HOME to exclude from your backup"
USAGE "[FLAG] [directory]? ..."

##############################################
# MAIN LOGIC

### Variables ###
exclusions="${HOME}/.backup_exclusions"
name=""
ARGS=("$@")

### Flags ###
for ((i = 0; i < ${#ARGS[@]}; i++)); do
	arg="${ARGS[i]}"

	case "$arg" in
	\? | -h | --help)
		HELP
		exit 0
		;;
	esac
done

# Create/edit the exclusions file
[ -f "${exclusions}" ] || {
	touch "${exclusions}"

	for f in "${HOME}"/{.,}*; do

		name="$(basename "$f")"

		if [[ "${name}" != "." ]] && [[ "${name}" != ".." ]]; then
			PRINT "${name}" >>"${exclusions}"
		fi

	done
}

${EDITOR:-nano} "${exclusions}"
