#!/usr/bin/env sh

##############################################
#   Author(s): RMCJ <rmichael1001@gmail.com>
#   Project: HeckerShell
#   Version: 1.0
#
#   Usage: crypto-rate [query]
#
#   Description:
#       Get the rate for a crypto currency
#
##############################################

curl "rate.sx/${1}"
