#!/usr/bin/env sh

##############################################
#   Author(s): RMCJ <rmichael1001@gmail.com>
#   Project: HeckerShell
#   Version: 1.0
#
#   Usage: qrcode [url]
#
#   Description:
#       Generate a QR Code for a url
#
##############################################

curl "qrenco.de/${1}"
