#!/usr/bin/env sh

##############################################
#   Author(s): RMCJ <rmichael1001@gmail.com>
#   Project: HeckerShell
#   Version: 1.0
#
#   Usage: shorten-url [url]
#
##############################################

curl -F "shorten=${1}" https://0x0.st
