#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: autostartctl
#	Version: 1.0
#
#	Usage: autostartctl [command] [args]
# 
# Description:
#   This utility provides tools to create, edit, list, and print
#   XDG Autostart desktop entries.
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/headers/02-api.sh

#############
# Core Code #
#############

# Variables
XDG_AUTOSTART="${HOME}/.config/autostart"
[[ -z "${EDITOR}" ]] && EDITOR=nano

filename=''
file=''
name=''
generic=''
binary=''
icon=''
apptype=''
categories=''
path=''

# Functions
append() {
  tee -a ${XDG_AUTOSTART}/${filename}.desktop
}

function TEMPLATE()
{
_template="
[Desktop Entry]
Name=${name}
Exec=${binary}
Type=${apptype}
Categories=${categories}
Hidden=true
"

[ -n "${generic}" ] && _template="${_template}\nGenericName=${generic}"
[ -n "${icon}" ] && _template="${_template}\nIcon=${icon}"
[ -n "${path}" ] && _template="${_template}\nPath=${path}"
}

makeEntry() {

    filename="${1}"
    [[ -z "${filename}" ]] && read -p "Entry Name: " filename

    file="${XDG_AUTOSTART}/${filename}.desktop"

    [[ -f "${file}" ]] && api.FAIL "${filename} already exists!"

    touch ${file}

    read -p "App Name: " name
    read -p "Executable Path: " binary
    read -p "Categories (semicolon separated): " categories
    read -p "Icon Path: " icon
    read -p "Generic Name: " generic

    apptype="Application"
    [[ -z "${categories}" ]] && categories="Utility;"

    # Add entry information to the file
    TEMPLATE
    api.PRINT ${_template} > ${file}

    api.LOG "Created ${filename}!"
    exit 0

}

editEntry() {

  filename="${1}"
  [[ -z "${filename}" ]] && read -p "Name of Entry: " filename

  file="${XDG_AUTOSTART}/${filename}.desktop"

  if [[ -f "${file}" ]]
  then
    ${EDITOR} ${file}
    api.LOG "Edited ${filename}!"
    exit 0
  else
    api.FAIL "Entry ${filename} does not exist!"
  fi
}

removeEntry() {
  filename="${1}"

  [[ -z "${filename}" ]] && read -p "Name of Entry: " filename

  file="${XDG_AUTOSTART}/${filename}.desktop"

  if [[ -e "${file}" ]]
  then
    rm -rf ${file}
    api.LOG "Removed ${filename}!"
    exit 0
  else
    api.FAIL "Entry ${filename} does not exist!"
  fi
}

listEntries() {
  ls -1 --group-directories-first ${XDG_AUTOSTART} | sed -e 's/\.desktop//'
  exit 0
}

printEntry() {
  filename="${1}"

  [[ -z "${filename}" ]] && read -p "Name of Entry: " filename

  file="${XDG_AUTOSTART}/${filename}.desktop"

  if [[ -e "${file}" ]]
  then
    api.PRINT 
    api.PRINT 
    cat ${file}
    exit 0
  else
    api.FAIL "${filename} does not exist!"
  fi
}

helpPrompt() {
  api.PRINT 
  api.PRINT "Manage XDG Autostart desktop entries."
  api.PRINT
  api.PRINT "Usage: `api.SCRIPTNAME` [command] [FLAGS]... [VALUES]..." 
  api.PRINT "Example: `api.SCRIPTNAME` c discord"
  api.PRINT "Example: `api.SCRIPTNAME` l"
  api.PRINT
  api.PRINT "Options: "
  api.PRINT "(c) create\t\tCreate an autostart entry and exit"
  api.PRINT "(e) edit\t\tEdit an autostart entry and exit"
  api.PRINT "(r) remove\t\tRemove an autostart entry and exit"
  api.PRINT "(l) list\t\tList all entries and exit"
  api.PRINT "(p) print\t\tDisplay an entry's contents and exit"
  api.PRINT
  api.PRINT "Miscellaneous:"
  api.PRINT "(h) help\t\tDisplay this help and exit"
  api.PRINT "(v) version\t\tDisplay this script's version and exit"
  exit 0
}

# Creates the autostart directory if it does not already exist.
[[ ! -d "${XDG_AUTOSTART}" ]] && mkdir ${XDG_AUTOSTART}

cmd=`api.LOWERCASE ${1}`

case "${cmd}" in
  c | create )
    makeEntry "${2}"
    ;;
  e | edit )
    editEntry "${2}"
    ;;
  r | remove )
    removeEntry "${2}"
    ;;
  l | list )
    listEntries
    ;;
  p | print )
    printEntry "${2}"
    ;;
  v | version )
    api.VERSION
    ;;
  \? | h | help )
    helpPrompt
    ;;
  * )
    [ -z "${cmd}" ] && helpPrompt || api.INVALID "${cmd}"
    ;;
esac
