#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: bootableusb
#	Version: 1.0
# 
#	Usage: bootableusb <iso> /path/to/drive
# 
#	Description:
#		Create a bootable USB drive from an
#		ISO file 
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/01-commons.sh

#############
# Core Code #
#############

dependency "dd"

if [ "$1" = "--help" ]
then
	echo "usage: bootableusb <iso> <drive>"
else
	sudo dd bs=4M if="$1" of="$2" conv=fdatasync
fi
