#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: bootableusb
#	Version: 1.0
# 
#	Usage: bootableusb <iso> /path/to/drive
# 
#	Description:
#		Create a bootable USB drive from an
#		ISO file 
##############################################

version='1.0'
author='Nidia Achrys'

#######################################################################
#							Helper Functions						  #
#######################################################################
function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function SCRIPTNAME()
{
	PRINT "${0##*/}"
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "${1}" | tr "[:upper:]" "[:lower:]"
}

function invalid()
{
	PRINT 
	PRINT "Invalid command \"${1}\". See \"`SCRIPTNAME` help\"."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \"`SCRIPTNAME` help\"."
	PRINT 
}

function dependency()
{
	[[ ! `command -v ${1}` ]] && PRINT "'${1}' is required to run this program." && exit 1
}

function version()
{
	PRINT "`SCRIPTNAME` v${version}"
	PRINT "Copyright (C) `date +"%Y"` ${author}"
	PRINT "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT
	PRINT "Written by ${author}."
}

#######################################################################
#								Core Code							  #
#######################################################################

dependency "dd"

if [ "$1" = "--help" ]
then
	echo "usage: bootableusb <iso> <drive>"
else
	sudo dd bs=4M if="$1" of="$2" conv=fdatasync
fi
