#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: debinstall
#	Version: 1.0
#
#	Usage: debinstall [command] [args]
#
#	Description:
#		Change this
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/01-api.sh

#############
# Core Code #
#############

DEPENDENCY 'apt'

name="${1}"
name="${name##*/}"

if [[ ! "${name##*.}" == "deb" ]]; then

	PRINT "That is not a valid deb file!"
	exit 1

fi

PRINT 
PRINT 
PRINT "Installing '${name}'..."
sudo apt install ${1} > /dev/null 2>&1

code=$?

[[ $code -eq 0 ]] && PRINT "Installed '${name}'.\n" || PRINT "Install failed.\n"

exit ${code}
