#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: debinstall
#	Version: 1.0
#
#	Usage: debinstall [command] [args]
#
#	Description:
#		Change this
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Core Code #
#############

api.required.command 'apt'

name="${1}"
name="${name##*/}"

if [[ ! "${name##*.}" == "deb" ]]; then

	api.std.failMsg "That is not a valid deb file!"

fi

api.std.printLn 
api.std.printLn 
api.std.logMsg "Installing '${name}'..."
sudo apt install ${1} > /dev/null 2>&1

code=$?

[[ $code -eq 0 ]] && api.std.logMsg "Installed '${name}'.\n" || api.std.failMsg "Install failed.\n"
