#!/usr/bin/env bash

minoutput=false

for (( i = 1 ; i <= $# ; i++ ))
do
	[[ ${!i} = "-l" ]] && minoutput=true
	[[ ${!i} = "--less" ]] && minoutput=true
done

for (( i = 1 ; i <= $# ; i++ ))
do
	arg=${!i}
	if [[ $arg =~ ^[0-9]+$ ]]
	then
		rand=$(( $RANDOM % ${arg} ))
		result=$(( ${rand} + 1 ))

		if [ ! $minoutput = true ]
		then
			echo -e "d${arg}: ${result}"
		else
			echo -e "${result}"
		fi
	fi
done
