#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: dice
#	Version: 1.0
#
#	Usage: dice [command] [args]
# 
#	Description:
#		Roll some dice!
##############################################

version='1.0'
author='Nidia Achrys'

PRINT()
{
	printf "%b\n" "${@}"
}

_RANDNUM()
{
	printf "%b" "$(( ${RANDOM} % ${1:-100} + 1 ))"
}

if [ $# -lt 1 ]
then
	PRINT "dice - Generates random numbers\n"
	PRINT "usage: dice [number...]"
	PRINT "example: dice 100 50 30 5 2"
  exit 1
fi

minoutput=false

for (( i = 1 ; i <= $# ; i++ ))
do
	[[ ${!i} = "-l" ]] && minoutput=true
	[[ ${!i} = "--less" ]] && minoutput=true
done

for (( i = 1 ; i <= $# ; i++ ))
do
	arg=${!i}
	if [[ $arg =~ ^[0-9]+$ ]]
	then
		result="$(_RANDNUM ${arg})"

		if [ ! $minoutput = true ]
		then
			PRINT "d${arg}: ${result}"
		else
			PRINT "${result}"
		fi
	fi
done
