#!/usr/bin/env bash
set -e

MIC_SOURCE=   # number from 'pactl list short sources'
OUTPUT_SINK=  # number from 'pactl list short sinks'
MIX_SOURCE=   # number for sink monitor of all mixed audio (without mic)
MIX_LOOPBACK= # number for mix loopback module (MIX_SOURCE -> OUTPUT_SINK)

cmd= 

# version
version="1.0"

function SCRIPTNAME()
{
	echo "$(basename ${0})"
}

function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "$1" | tr '[:upper:]' '[:lower:]'
}

function invalid()
{
	PRINT 
	PRINT "Invalid command '${1}'. See \'`SCRIPTNAME` help\'."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \'`SCRIPTNAME` help\'."
	PRINT 
}

function setup() {
	pactl list short modules | grep -q 'Virtual_Sink' && return

	if [ -z "$MIC_SOURCE" ]; then
		first_source=$(pactl list short sources | head -1 | awk '{print $1;}') # e.g. 0
		pactl list short sources
		read -p ">> Source (input) number to use [$first_source]: " user_source
		[ -z "$user_source" ] && user_source=$first_source
		MIC_SOURCE=$user_source
		PRINT 
		first_sink=$(pactl list short sinks | head -1 | awk '{print $1;}') # e.g. 1
		pactl list short sinks
		read -p ">> Sink (output) number to use [$first_sink]: " user_sink
		[ -z "$user_sink" ] && user_sink=$first_sink
		OUTPUT_SINK=$user_sink
		PRINT 
	fi

	pactl load-module module-null-sink sink_name=Virtual_Output sink_properties=device.description=Virtual_Output > /dev/null
	pactl load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink > /dev/null
	MIX_SOURCE=$(pactl list short sources | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 14

	pactl load-module module-loopback latency_msec=1 source=$MIC_SOURCE sink=Virtual_Output > /dev/null
	pactl load-module module-loopback latency_msec=1 source=$MIX_SOURCE sink=Virtual_Output > /dev/null
	MIX_LOOPBACK=$(pactl load-module module-loopback latency_msec=1 source=$MIX_SOURCE sink=$OUTPUT_SINK)
}

function cleanup() {
	virtual_sink=$(pactl list short modules | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 30
	[ -z "$virtual_sink" ] && return
	read -p '>> Press enter to unload PulseAudio modules for the virtual mix...'

	[ ! -z "$MIX_LOOPBACK" ] && pactl unload-module $MIX_LOOPBACK || pactl unload-module module-loopback
	pactl list short modules | grep -E 'Virtual_(Sink|Output)' | awk '{print $1;}' | xargs -L1 pactl unload-module
}

function run()
{
	setup
	PRINT ">> Your virtual mix is currently active! Feel free to open e.g. 'pavucontrol' now."
	PRINT 
	PRINT ">> For software that should have their audio included in the mix, move them"
	PRINT "   to the 'Virtual_Sink' under the 'Playback' tab."
	PRINT ">> For software that should capture the mixed audio, head to the 'Recording'"
	PRINT "   tab and make the software use 'Monitor of Virtual_Output' as their input."
	PRINT 
	cleanup
}

function help_prompt()
{
	PRINT 
	PRINT "Enable/disable sound sharing for discord with Pulseaudio"
	PRINT 
	PRINT "Usage: `SCRIPTNAME` [command] [args]"
	PRINT "Example: `SCRIPTNAME` start"
	PRINT
	PRINT "Commands:"
	PRINT "(s) start\tStart the sound sharing"
	PRINT "(p) stop\tStop the sound sharing"
	PRINT "(i) shell\tUse the interactive shell to work with `SCRIPTNAME`"
	PRINT "(e) exit\t(Shell only) Exit the script"
	PRINT
	PRINT "Miscellaneous:"
	PRINT "(h) help\tShow this help menu"
	PRINT "(v) version\tShow this script's version"
	PRINT 
}

function version()
{
	PRINT 
	PRINT "`SCRIPTNAME` v${version}"
	PRINT 
	PRINT "Copyright (C) `date +"%Y"` Nidia Achrys"
	PRINT "License GPLv3+: GNU GPL version 3 or later https://gnu.org/licenses/gpl.html."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT 
	PRINT "Written by Nidia Achrys."
	PRINT 
}

function shell()
{
	while [ "${cmd}" != "exit" ];
	do
		clear
		PRINT "Discord Sound Sharing Console"
		PRINT 
		PRINT "Enter a command or 'help' for a list of commands."
		PRINT 
		read -p "> " cmd

		og_cmd="${cmd}"
		cmd=`lowercase "${cmd}"`

		case "$cmd" in
			s | start )
				run
				pause
				;;
			p | stop )
				systemctl --user restart pulseaudio
				pause
				;;
			\? | h | help )
				help_prompt
				pause
				;;
			v | version )
				version
				pause
				;;
			e | exit )
				clear
				exit 0
				;;
			* )
				if [ -z "${cmd}" ];
				then
					emptycmd
					pause
				else
					invalid "${cmd}"
					pause
				fi
				;;
		esac
	done
}


cmd=`lowercase "${1}"`

case "${cmd}" in
	s | start )
		run
		;;
	p | stop )
		systemctl --user restart pulseaudio
		;;
	\? | h | help )
		help_prompt
		;;
	v | version )
		version
		;;
	i | shell )
		shell
		;;
	* )
		if [ -z "${cmd}" ];
		then
			emptycmd
		else
			invalid "${cmd}"
		fi
		;;
esac