#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: emojictl
#	Version: 1.0
# 
#	Usage: emojictl [command] [args]
# 
#	Description:
#		Install/uninstall Noto Color Emoji on Linux
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/headers/02-api.sh

#############
# Core Code #
#############

# Dependencies
api.DEPENDENCY "wget"
api.DEPENDENCY "unzip"
api.DEPENDENCY "fc-cache"

# Noto Emoji package link
EMOJIPKG="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"

# Fontconfig file links
FONTCONFIGS=(
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/01-dejavu.conf"
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/02-mozilla.conf"
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/03-emoji.conf"
)

# Directories
CONFDIR=$HOME/.config/fontconfig/conf.d
NOTOPKG="$HOME/Downloads/$(basename ${EMOJIPKG})"
TEMP=$HOME/Downloads/temp
FONTS=$HOME/.fonts
FILE=$HOME/.fonts/NotoColorEmoji.ttf

# cmd
cmd=""

function preparedirs()
{
	# Make the config directory and move to it
	[ ! -d $CONFDIR ] && mkdir -p $CONFDIR
	[ ! -d $FONTS ] && mkdir -p $FONTS
	[ -d $TEMP ] && rm -rf $TEMP
	[ -f $FILE ] && rm -rf $FILE
	[ -f $NOTOPKG ] && rm -f $NOTOPKG
}

function installer()
{
	clear

	# Make the config directory and move to it
	preparedirs
	cd $CONFDIR

	# Download the fontconfig files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename $file)
		rm -f $name
		wget $file
	done

	# Download noto emoji font
	cd $TEMP
	wget $EMOJIPKG

	# Install emojis
	unzip NotoColorEmoji-unhinted.zip
	mv NotoColorEmoji.ttf $FONTS
	fc-cache -fv
	rm -rf $TEMP
	
	# Post
	api.PRINT 
	api.PRINT 
	api.LOG "Install finished."
	api.PRINT 
	api.PAUSE
}

function uninstaller()
{
	clear
	preparedirs

	# Remove the font file
	rm -f ${FONTS}/NotoColorEmoji.ttf

	# Remove the config files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename ${file})
		rm -f ${CONFDIR}/${name}
	done

	# Reload the font cache
	fc-cache -fv
	
	# Post
	api.PRINT 
	api.PRINT 
	api.LOG "Uninstall finished."
	api.PRINT 
	api.PAUSE
}

function help_prompt()
{
	api.PRINT 
	api.PRINT "Manage emoji installation on your Linux system"
	api.PRINT 
	api.PRINT "Usage: `api.SCRIPTNAME` [command] [args]"
	api.PRINT "Example: `api.SCRIPTNAME` install"
	api.PRINT
	api.PRINT "Commands:"
	api.PRINT "(i) install\tInstall Noto Color Emoji"
	api.PRINT "(u) uninstall\tUninstall Noto Color Emoji"
	api.PRINT "(e) exit\t(Shell only) exit the shell"
	api.PRINT 
	api.PRINT "Miscellaneous:"
	api.PRINT "(h) help\tShow this help menu"
	api.PRINT "(v) version\tShow this script's version"
	api.PRINT 
}

cmd=`api.LOWERCASE "${1}"`

case "${cmd}" in

	install | i )
		installer
		exit 0
		;;
	uninstall | u )
		uninstaller
		exit 0
		;;
	help | h | \? )
		help_prompt
		exit 0
		;;
	version | v )
		api.VERSION
		exit 0
		;;
	* )
		[ -z "${cmd}" ] && help_prompt || api.INVALID && exit 1
		;;

esac
