#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: emojictl
#	Version: 1.0
# 
#	Usage: emojictl [command] [args]
# 
#	Description:
#		Install/uninstall Noto Color Emoji on Linux
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

# Help
api.script.description "Manage emoji installation on your Linux system"
api.script.usage "[command] [args]"
api.script.example "install"

api.script.option "i" "install" "Install Noto Color Emoji"
api.script.option "u" "uninstall" "Uninstall Noto Color Emoji"

#############
# Core Code #
#############

# Dependencies
api.required.command "wget"
api.required.command "unzip"
api.required.command "fc-cache"

# Noto Emoji package link
EMOJIPKG="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"

# Fontconfig file links
FONTCONFIGS=(
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/01-dejavu.conf"
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/02-mozilla.conf"
"https://raw.githubusercontent.com/garman1001/dotfiles/master/configs/fontconfig/conf.d/03-emoji.conf"
)

# Directories
CONFDIR=$HOME/.config/fontconfig/conf.d
NOTOPKG="$HOME/Downloads/$(basename ${EMOJIPKG})"
TEMP=$HOME/Downloads/temp
FONTS=$HOME/.fonts
FILE=${FONTS}/NotoColorEmoji.ttf

# cmd
cmd=""

emojictl.prepare ()
{
	# Make the config directory and move to it
	[ ! -d $CONFDIR ] && mkdir -p $CONFDIR
	[ ! -d $FONTS ] && mkdir -p $FONTS
	[ -d $TEMP ] && rm -rf $TEMP
	[ -f $FILE ] && rm -rf $FILE
	[ -f $NOTOPKG ] && rm -f $NOTOPKG
}

emojictl.emojis.install ()
{
	clear

	# Make the config directory and move to it
	emojictl.prepare
	cd $CONFDIR

	# Download the fontconfig files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename $file)
		rm -f $name
		wget $file
	done

	# Download noto emoji font
	cd $TEMP
	wget $EMOJIPKG

	# Install emojis
	unzip NotoColorEmoji-unhinted.zip
	mv NotoColorEmoji.ttf $FONTS
	fc-cache -fv
	rm -rf $TEMP
	
	# Post
	clear
	api.std.printLn 
	api.std.logMsg "Install finished."
	api.std.printLn 
	api.std.pause
	clear
}

emojictl.emojis.uninstall ()
{
	clear
	emojictl.prepare

	# Remove the font file
	rm -f ${FONTS}/NotoColorEmoji.ttf

	# Remove the config files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename ${file})
		rm -f ${CONFDIR}/${name}
	done

	# Reload the font cache
	fc-cache -fv
	
	# Post
	clear
	api.std.printLn 
	api.std.logMsg "Uninstall finished."
	api.std.printLn 
	api.std.pause
	clear
}

cmd=`api.string.toLowerCase "${1}"`

case "${cmd}" in

	install | i )
		emojictl.emojis.install
		exit 0
		;;
	uninstall | u )
		emojictl.emojis.uninstall
		exit 0
		;;
	help | h | \? )
		api.script.help
		exit 0
		;;
	version | v )
		api.script.version
		exit 0
		;;
	* )
		[ -z "${cmd}" ] && api.script.help || api.errors.invalidCommand && exit 1
		;;

esac
