#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: extract
#	Version: 1.0
#
#	Usage: extract [command] [args]
#
#	Description:
#		Extract any archive file
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/01-api.sh

#############
# Core Code #
#############

if [ $# -eq 0 ]
then
	PRINT 
	PRINT "usage: `SCRIPTNAME` <file>\n"
	PRINT 
	PRINT "supported file types:"
	PRINT "tar.bz2, tar.gz, bz2, rar, gz, tar, tbz2, tgz"
	PRINT "zip, Z, 7z, deb, tar.xz, tar.zst"
	PRINT 
	exit 0
elif [ ! -f "${1}" ]
then
	PRINT "`SCRIPTNAME`: '${1}' is not a file."
	exit 1
else
	PRINT "`SCRIPTNAME`: Unknown error"
	exit 1
fi

case "${1}" in
	*.tar.bz2)
		DEPENDENCY "tar"
		tar xjf ${1}
		;;
	*.tar.gz)
		DEPENDENCY "tar"
		tar xzf ${1}
		;;
	*.bz2)
		DEPENDENCY "bunzip"
		bunzip ${1}
		;;
	*.rar)
		DEPENDENCY "unrar"
		unrar x ${1}
		;;
	*.gz)
		DEPENDENCY "gunzip"
		gunzip ${1}
		;;
	*.tar)
		DEPENDENCY "tar"
		tar xf ${1}
		;;
	*.tbz2)
		DEPENDENCY "tar"
		tar xjf ${1}
		;;
	*.tgz)
		DEPENDENCY "tar"
		tar xzf ${1}
		;;
	*.zip)
		DEPENDENCY "unzip"
		unzip ${1}
		;;
	*.Z)
		DEPENDENCY "uncompress"
		uncompress ${1}
		;;
	*.7z)
		DEPENDENCY "7z"
		7z x ${1}
		;;
	*.deb)
		DEPENDENCY "ar"
		ar x ${1}
		;;
	*.tar.xz)
		DEPENDENCY "tar"
		tar xf ${1}
		;;
	*.tar.zst)
		DEPENDENCY "unzstd"
		unzstd ${1}
		;;
	*)
		PRINT "`SCRIPTNAME`: '${1}' cannot be extracted via ${SCRIPTNAME}"
		;;
esac
