#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: extract
#	Version: 1.0
#
#	Usage: extract [command] [args]
#
#	Description:
#		Extract any archive file
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Core Code #
#############

if [ $# -eq 0 ]
then
	api.PRINT 
	api.PRINT "usage: `api.SCRIPTNAME` <file>\n"
	api.PRINT 
	api.PRINT "supported file types:"
	api.PRINT "tar.bz2, tar.gz, bz2, rar, gz, tar, tbz2, tgz"
	api.PRINT "zip, Z, 7z, deb, tar.xz, tar.zst"
	api.PRINT 
	exit 0
elif [ ! -f "${1}" ]
then
	api.FAIL "'${1}' is not a file."
else
	api.FAIL "Unknown error"
fi

case "${1}" in
	*.tar.bz2)
		api.DEPENDENCY "tar"
		tar xjf ${1}
		;;
	*.tar.gz)
		api.DEPENDENCY "tar"
		tar xzf ${1}
		;;
	*.bz2)
		api.DEPENDENCY "bunzip"
		bunzip ${1}
		;;
	*.rar)
		api.DEPENDENCY "unrar"
		unrar x ${1}
		;;
	*.gz)
		api.DEPENDENCY "gunzip"
		gunzip ${1}
		;;
	*.tar)
		api.DEPENDENCY "tar"
		tar xf ${1}
		;;
	*.tbz2)
		api.DEPENDENCY "tar"
		tar xjf ${1}
		;;
	*.tgz)
		api.DEPENDENCY "tar"
		tar xzf ${1}
		;;
	*.zip)
		api.DEPENDENCY "unzip"
		unzip ${1}
		;;
	*.Z)
		api.DEPENDENCY "uncompress"
		uncompress ${1}
		;;
	*.7z)
		api.DEPENDENCY "7z"
		7z x ${1}
		;;
	*.deb)
		api.DEPENDENCY "ar"
		ar x ${1}
		;;
	*.tar.xz)
		api.DEPENDENCY "tar"
		tar xf ${1}
		;;
	*.tar.zst)
		api.DEPENDENCY "unzstd"
		unzstd ${1}
		;;
	*)
		api.FAIL "'${1}' cannot be extracted via ${api.SCRIPTNAME}"
		;;
esac
