#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: gitupdate
#	Version: 1.0
#
#	Usage: gitupdate [command] [args]
#
#	Description:
#		Change this
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/01-api.sh

#############
# Core Code #
#############

# This is where you put your script's functions, variables, logic, etc.

for dir in `find . -name '.git' | xargs -i dirname {}`
do
	cd ${dir}
	
	# Print the directory name
	pwd

	# Update the repository
	git pull

	# Change back to home directory
	cd -
done
