#!/usr/bin/env bash

PRINT() {
	printf "%b\n" "$@" 
}

_fetchSessionID() {
	SESSIONS=( "$(loginctl list-sessions | grep $(whoami) | awk 'BEGIN {ORS=" "}; {print $1}')" )
	return 0
}

_lock() { 
	for SESSION in ${SESSIONS[@]}; do
		loginctl lock-session "$SESSION"
	done

	return 0
}

_unlock() {
	for SESSION in ${SESSIONS[@]}; do
		loginctl unlock-session "$SESSION"
	done

	return 0
}

_logout() {
	for SESSION in ${SESSIONS[@]}; do
		loginctl kill-session "$SESSION"
	done

	return 0
}

_help() {
	PRINT "lockd - Lock/Unlock your computer from the command line"
	PRINT
	PRINT "Commands:"
	PRINT "- l, lock\tLock your computer"
	PRINT "- u, unlock\tUnlock your computer"
	PRINT "- e, logout\tLogout of all sessions"
	PRINT "- i, id\t\tView your session ID"
	PRINT "- h, help\tView this prompt"
	PRINT
	return 0
}

# Get the Session ID
_fetchSessionID

# Get the cli command
arg="$(printf '%b' $1 | tr '[:upper:]' '[:lower:]')"

case "$arg" in

	l | lock )
		_lock ;;
	u | unlock )
		_unlock ;;
	e | logout )
		_logout ;;
	i | id )
		PRINT "${SESSIONS[@]}" ;;
	h | help )
		_help ;;
	* )
		[[ -z "${1}" ]] && _help && exit 0
		PRINT "Invalid Command '${arg}'!" ;;
esac

