#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: mansplain
#	Version: 1.0
#
#	Usage: mansplain [command] [args]
#
#	Description:
#		Use dmenu to view manpages in PDF format
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Core Code #
#############

api.DEPENDENCY "rofi"
api.DEPENDENCY "zathura"
api.DEPENDENCY "ps2pdf"

function menu ()
{
	rofi -dmenu -columns 3 -disable-history -p "Manpage" -mesg "Pick the manpage you want to view in Zathura."
}

name=`man -k . | awk '{print $1}' | menu`

[[ -z "${name}" ]] && exit 1

man -t ${name} | ps2pdf - ${name}.pdf

[[ -f "${name}.pdf" ]] || exit 1

zathura "${name}.pdf"
rm -rf "${name}.pdf"
