#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: minecraftctl
#	Version: 1.0
#
#	Usage: minecraftctl [command] [args]
#
#	Description:
#		Manage minecraft installations
##############################################

PRINT ()
{
	printf "%b\n" "${@}"
	return $?
}

PAUSE ()
{
	read -p "Press ENTER to continue..." pause_entry
	return 0
}

desktopEntry="/usr/share/applications/minecraft-launcher.desktop"
downloadLink="https://launcher.mojang.com/download/Minecraft.deb"
launcherPath1="/opt/minecraft-launcher"
launcherPath2="/opt/minecraft"

minecraftctl.install()
{
	# Clear Screen	
	clear

	# Variables
	local link="${downloadLink}"
	local dentry="${desktopEntry}"

	# Download
	cd $HOME/Downloads
	if [[ -f "Minecraft.deb" ]]
	then
		read -p "Do you want to remove the old Minecraft debfile (y/N)? " ans
		ans="$(printf '%b' ${ans} | tr '[:upper:]' '[:lower:]')"

		case "${ans}" in

			y | yes ) clear; rm -f ./Minecraft.deb && wget "${link}" ;;

			* ) PRINT "Not removing deb file." ;;

		esac
	else
		wget "${link}"
	fi

	PRINT "Installing Minecraft..."

	# Install the deb file
	sudo ar xf Minecraft.deb
	sudo tar xf data.tar.xz -C /
	sudo rm control.tar.gz data.tar.xz debian-binary

	# Desktop Entry
	entryText="Exec=env JAVA_HOME=/usr/lib64/openjdk-8 ${launcherPath1}/minecraft-launcher"

	# Create the desktop entry
	PRINT "${entryText}" | sudo tee -a "${dentry}"

	# Confirmation
	clear
	PRINT "Installation finished."
	PRINT
	PAUSE
	clear
}

minecraftctl.remove()
{
	# Clear screen
	clear

	# Remove files
	sudo rm -rf ${launcherPath1} && sudo rm -rf ${launcherPath2} && PRINT "Removed Launcher."
	sleep 1.5

	sudo rm -f ${desktopEntry} && PRINT "Removed desktop entry."
	sleep 1.5

	# Confirmation
	PRINT "Uninstallation finished."
	PAUSE
	clear
}

minecraftctl.update()
{
	minecraftctl.remove
	minecraftctl.install
}

_help()
{
	PRINT 
	PRINT "minecraftctl - Manage minecraft from the terminal"
	PRINT
	PRINT "Commands:"
	PRINT
	PRINT "(i) install\n\t- Install minecraft"
	PRINT "(r) remove\n\t- Uninstall minecraft"
	PRINT "(u) update\n\t- Update minecraft"
	PRINT "(h) help\n\t- Show this help menu"
}

cmd="$(printf '%b' $1 | tr '[:upper:]' '[:lower:]')"

case "${cmd}" in
	i | install )
		minecraftctl.install
		;;
	r | remove )
		minecraftctl.remove
		;;
	u | update )
		minecraftctl.update
		;;
	\? | h | help )
		_help
		;;
	* )
		[ -z "${cmd}" ] && _help || PRINT "'${1}' is an invalid subcommand!"
		;;
esac
