#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: mp3dl
#	Version: 1.0
#
#	Usage: mp3dl [command] [args]
#
#	Description:
#		Download youtube videos and convert
#		them to mp3 files
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Core Code #
#############

api.required.command "youtube-dl"

DOWNDIR=$HOME/Downloads/Music
[ ! -d $DOWNDIR ] && mkdir $DOWNDIR
cd $DOWNDIR

youtube-dl --prefer-ffmpeg --add-metadata --output '%(title)s.%(ext)s' --extract-audio --audio-format mp3 $@
