#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: mp3dl
#	Version: 1.0
#
#	Usage: mp3dl [command] [args]
#
#	Description:
#		Download youtube videos and convert
#		them to mp3 files
##############################################

version='1.0'
author='Nidia Achrys'

#######################################################################
#							Helper Functions						  #
#######################################################################
function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function SCRIPTNAME()
{
	PRINT "${0##*/}"
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "${1}" | tr "[:upper:]" "[:lower:]"
}

function invalid()
{
	PRINT 
	PRINT "Invalid command \"${1}\". See \"`SCRIPTNAME` help\"."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \"`SCRIPTNAME` help\"."
	PRINT 
}

function dependency()
{
	[[ ! `command -v ${1}` ]] && PRINT "'${1}' is required to run this program." && exit 1
}

function version()
{
	PRINT "`SCRIPTNAME` v${version}"
	PRINT "Copyright (C) `date +"%Y"` ${author}"
	PRINT "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT
	PRINT "Written by ${author}."
}

#######################################################################
#								Core Code							  #
#######################################################################

dependency "youtube-dl"

DOWNDIR=$HOME/Downloads/Music
[ ! -d $DOWNDIR ] && mkdir $DOWNDIR
cd $DOWNDIR

youtube-dl --prefer-ffmpeg --add-metadata --output '%(title)s.%(ext)s' --extract-audio --audio-format mp3 $@
