#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: mp3dl
#	Version: 1.0
#
#	Usage: mp3dl [command] [args]
#
#	Description:
#		Download youtube videos and convert
#		them to mp3 files
##############################################

PRINT()
{
	printf "%b\n" "${@}"
}

[[ -x "$(which youtube-dl)" ]] && PRINT "youtubedl is required to run this program." && exit 1

DIR=$HOME/Downloads/Music

[[ -d $DIR ]] || mkdir $DIR

cd $DIR

youtube-dl \
	--prefer-ffmpeg \
	--add-metadata \
	--output '%(title)s.%(ext)s' \
	--extract-audio \
	--audio-format mp3 ${@}
