#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: pacmirrors
#	Version: 1.0
#
#	Usage: pacmirrors [command] [args]
#
#	Description:
#		Refresh pacman mirrors (Arch distros only)
##############################################

version='1.0'
author='Nidia Achrys'

#######################################################################
#							Helper Functions						  #
#######################################################################
function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function SCRIPTNAME()
{
	PRINT "${0##*/}"
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "${1}" | tr "[:upper:]" "[:lower:]"
}

function invalid()
{
	PRINT 
	PRINT "Invalid command \"${1}\". See \"`SCRIPTNAME` help\"."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \"`SCRIPTNAME` help\"."
	PRINT 
}

function dependency()
{
	[[ ! `command -v ${1}` ]] && PRINT "'${1}' is required to run this program." && exit 1
}

function version()
{
	PRINT "`SCRIPTNAME` v${version}"
	PRINT "Copyright (C) `date +"%Y"` ${author}"
	PRINT "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT
	PRINT "Written by ${author}."
}

#######################################################################
#								Core Code							  #
#######################################################################

dependency "pacman"

refresh()
{
  mirrorlist=/etc/pacman.d/mirrorlist
  backupfile=/etc/pacman.d/mirrorlist.backup
  
  [[ -f $backupfile ]] && sudo rm -f $backupfile
  sudo cp $mirrorlist $backupfile
  sudo reflector --sort rate --protocol https --latest 30 --verbose --save $mirrorlist
}

if [[ `command -v reflector` ]]
then
  refresh
else
  pacman -S reflector
  refresh
fi
