#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: pacmirrors
#	Version: 1.0
#
#	Usage: pacmirrors [command] [args]
#
#	Description:
#		Refresh pacman mirrors (Arch distros only)
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/headers/02-api.sh

#############
# Core Code #
#############

api.DEPENDENCY "pacman"

refresh()
{
  mirrorlist=/etc/pacman.d/mirrorlist
  backupfile=/etc/pacman.d/mirrorlist.backup
  
  [[ -f $backupfile ]] && sudo rm -f $backupfile
  sudo cp $mirrorlist $backupfile
  sudo reflector --sort rate --protocol https --latest 30 --verbose --save $mirrorlist
}

if [[ `command -v reflector` ]]
then
  refresh
else
  pacman -S reflector
  refresh
fi
