#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: pkg
#	Version: 1.0
#
#	Usage: pkg [command] [args]
#
#	Description:
#		This utility manages software across distributions
##############################################

version='1.0'
author='Nidia Achrys'

#######################################################################
#							Helper Functions						  #
#######################################################################
function SCRIPTNAME()
{
	echo "${0##*/}"
}

function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "${1}" | tr "[:upper:]" "[:lower:]"
}

function invalid()
{
	PRINT 
	PRINT "Invalid command \"${1}\". See \"`SCRIPTNAME` help\"."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \"`SCRIPTNAME` help\"."
	PRINT 
}

function version()
{
	PRINT "`SCRIPTNAME` v${version}"
	PRINT "Copyright (C) `date +"%Y"` ${author}"
	PRINT "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT
	PRINT "Written by ${author}."
}

#######################################################################
#								Core Code							  #
#######################################################################

SEARCH=""
UPDATE=""
INSTALL=""
UNINSTALL=""

ARGS=()

package_managers="apt, pacman, yay"

help_prompt()
{
    PRINT 
    PRINT "Install, remove, search, and update software. Cross Platform."
    PRINT
    PRINT "Usage: `SCRIPTNAME` [command] [args]"
    PRINT "Example: `SCRIPTNAME` search <package>"
    PRINT
    PRINT "Note: Only supports the following package managers: ${package_managers}"
    PRINT
    PRINT "Commands"
    PRINT "(i) install\t\tInstall Software"
    PRINT "(r) remove\t\tUninstall Software"
    PRINT "(s) search\t\tSearch for software"
    PRINT "(u) update\t\tUpdate your software"
    PRINT 
    PRINT "Miscellaneous"
    PRINT "(h) help\t\tShow this prompt"
    PRINT "(v) version\t\tPrint the version of this script"
}

if [[ `command -v pacman` ]];
then
    INSTALL="pacman -Sy"
    UNINSTALL="pacman -Rns"
    SEARCH="pacman -Ss"
    UPDATE="pacman -Syyyu"
elif [[ `command -v yay` ]];
then
    INSTALL="yay -Sy"
    UNINSTALL="yay -Rns"
    SEARCH="yay -Ss"
    UPDATE="yay -Syyyu"
elif [[ `command -v apt` ]];
then
    INSTALL="sudo apt install"
    UNINSTALL="sudo apt remove"
    SEARCH="sudo apt search"
    UPDATE="sudo apt update && sudo apt upgrade"
else
    PRINT "Your distro is not currently supported!"
    exit 1
fi

ARGS=("$@")

unset ARGS[0]
unset ARGS[1]

cmd=`lowercase ${1}`

case "${cmd}" in

    i | install )
        eval "${INSTALL} ${ARGS[@]}"
        exit 0
        ;;
    r | remove )
        eval "${UNINSTALL} ${ARGS[@]}"
        exit 0
        ;;
    s | search )
        eval "${SEARCH} ${ARGS[@]}"
        exit 0
        ;;
    u | update )
        eval "${UPDATE} ${ARGS[@]}"
        exit 0
        ;;
    \? | h | help )
        help_prompt
        exit 0
        ;;
    v | version )
        version
        exit 0
        ;;
    * )
		if [ -z "${cmd}" ];
		then
			emptycmd
		else
			invalid "${1}"
		fi
		exit 0
		;;

esac
