#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: pkglists
#	Version: 1.0
#
#	Usage: pkglists [command] [args]
#
#	Description:
#		Make lists of packages installed in
#		pacman (arch distros only)
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/libs/01-api.sh

#############
# Core Code #
#############

api.required.command "pacman"

pkglists.lists.create ()
{
    pacmanlist="$(pacman -Qqe | grep -v '`pacman -Qq base`' | grep -v '`pacman -Qqm`')"
    aurlist="$(pacman -Qqm)"
}

pkglists.lists.write ()
{
    # Goto the Downloads directory
    cd $HOME/Downloads
    
    # Write lists
    api.std.printLn "$pacmanlist" > pacmanlist.txt
    api.std.printLn "$aurlist" > aurlist.txt
    cat pacmanlist.txt aurlist.txt > allpkgs.txt
}

pkglists.lists.create
pkglists.lists.write

# Confirmation
api.std.logMsg "Created lists in ${HOME}/Downloads!"
