#!/usr/bin/env bash
#
#
# Program: purge-wine
# Description: Uninstalls WINE and all related desktop entries.
# Usage: purge-wine
#
# Author: Roy Conn (garman1001)
# License: GPLv3

pacman=$(command -v pacman)
apt=$(command -v apt)

if [[ $pcman ]];
then
	sudo pacman -Rnsv wine wine-gecko wine-mono winetricks wine-staging
elif [[ $apt ]];
then
	sudo apt remove wine-stable-amd wine-stable-i386 wine-stable
	sudo apt autoremove
fi

# Removes all leftover wine applications
cd $HOME
rm -rf .wine

# The lines below will remove all entries for any windows software
# installed with WINE from your application menu(s). Make sure to
# remove them using your menu editor as well.

rm -f $HOME/.config/menus/applications-merged/wine*
rm -rf $HOME/.local/share/applications/wine
rm -f $HOME/.local/share/desktop-directories/wine*
rm -f $HOME/.local/share/icons/????_*.{xpm,png}
rm -f $HOME/.local/share/icons/*-x-wine-*.{xpm,png}
