#!/usr/bin/env bash

refresh()
{
  mirrorlist=/etc/pacman.d/mirrorlist
  backupfile=/etc/pacman.d/mirrorlist.backup
  
  [[ -f $backupfile ]] && sudo rm -f $backupfile
  sudo cp $mirrorlist $backupfile
  sudo reflector --sort rate --protocol https --latest 30 --verbose --save $mirrorlist
}

if [[ `command -v reflector` ]]
then
  refresh
else
  [[ ! `command -v pacman` ]] && echo "This script can only run on Arch Linux." && exit 1
  pacman -S reflector
  refresh
fi
