#!/usr/bin/env bash

RSYNCDIR()
{
    rsync -vhPrauL --delete $@
}

RSYNCFILE()
{
    rsync -vhPau --delete $@
}

declare -- TARGET	 # Non-hidden files in target directory
declare -- HIDDENTARGET  # Hidden files in target directory
declare -- FILE		 # Variable to store filename in loops

[ -z "${1}" ] && echo -e "Must specify a target directory!" && exit 1
[ ! -d "${1}" ] && echo -e "'${1}' is not a directory!" && exit 1

for FILE in ${1}/*
do
    [ -d "${FILE}" ] && RSYNCDIR "${FILE}" "${HOME}"
    [ -f "${FILE}" ] && RSYNCFILE "${FILE}" "${HOME}"
done

echo "Restored unhidden files!"

for FILE in ${1}/.*
do
    [ -d "${FILE}" ] && RSYNCDIR "${FILE}" "${HOME}"
    [ -f "${FILE}" ] && RSYNCFILE "${FILE}" "${HOME}"
done

echo "Restored hidden files!"

unset TARGET
unset HIDDENTARGET
unset FILE
