#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: toaster
#	Version: 1.0
#
#	Usage: toaster [command] [args]
#
#	Description:
#		Toaster simulator
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/headers/02-api.sh

#############
# Core Code #
#############

broken="false"

makeToast()
{
	read -p "Pieces: " pieces

	api.std.printLn 
	[[ ! ${pieces} =~ [0-9]+ ]] && api.std.printLn "You must specify a number!" && return 1

	api.std.printLn "Making ${pieces} piece(s) of toast..."
	sleep 3
	api.std.printLn "Made ${pieces} piece(s) of toast."

	api.std.printLn 
	api.std.pause
	return 0
}

commitBath()
{
	api.std.printLn 
	api.std.printLn "Committing toaster bath..."
	sleep 3

	successful="`api.std.randomNumber 2`"

	if [ "${broken}" != "false" ]; then
		api.std.printLn "The toaster was previously broken. Find a new toaster?"; sleep 3; api.std.pause
		broken="true"
		return 1
	fi

	if [ "${successful}" == "1" ]; then
		api.std.printLn "The toaster wasn't plugged in, and has been damaged by the water."; sleep 3; api.std.pause
	else
		api.std.printLn "You have died. Have a nice afterlife!"; sleep 3; api.std.pause
	fi

	broken="true"

	api.std.printLn 
	return 0
}

throwToaster()
{
	read -p "Target: " target

	api.std.printLn 
	api.std.printLn "You have thrown a toaster at ${target}."
	sleep 3

	successful="`api.std.randomNumber 2`"

	if [ "${successful}" == "1" ]; then
		api.std.printLn "You didn't aim properly, and the toaster hit the wall."; api.std.pause
	else
		api.std.printLn "Your aim was perfect and you hit ${target} in the head."; api.std.pause
	fi

	broken="true"
	api.std.printLn 
	return 0
}

cmd=""

while [[ "${cmd}" != "4" ]]; do
	clear
	api.std.printLn "Toaster Menu"
	api.std.printLn 
	api.std.printLn 
	api.std.printLn "1. Make Toast"
	api.std.printLn "2. Commit Toaster Bath"
	api.std.printLn "3. Throw Toaster"
	api.std.printLn "4. Exit"
	api.std.printLn
	read -p "> " cmd

	cmd=`api.string.toLowerCase "${cmd}"`

	case "${cmd}" in

		1 | 'make toast' | 'make me a sammich bitch' )
			makeToast
			;;
		2 | 'commit toaster bath' )
			commitBath
			;;
		3 | 'throw toaster' )
			throwToaster
			;;
		4 | 'exit' )
			clear
			exit 0
			;;
		* )
			api.std.errorMsg "\nInvalid option!\n"
			api.std.pause
			;;

	esac
done
