#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: trash
#	Version: 1.0
#
#	Usage: trash [command] [args]
#
#	Description:
#		This utility manages your trash bin.
##############################################

version='1.0'
author='Nidia Achrys'

# Source common script functions
source $SCRIPTS/headers/02-api.sh

#############
# Core Code #
#############

# This is where you put your script's functions, variables, logic, etc.

declare -- TRASHINFO
declare -- FILENAME
declare -- FILEINFO
declare -- DELPATH
declare -- DELDATE
declare -- FILEPATH
declare -- FILEINFO
declare -- RESTOREPATH

TRASHDIRS=$HOME/.local/share/Trash
TRASHINFO=$TRASHDIRS/info
[ -z "$TRASH" ] && TRASH=$TRASHDIRS/files

checkFile()
{
  if [ -n "$1" ];
  then
    FILE="$1"
  else
    api.FAIL "You must specify a FILE."
  fi
}

getPath()
{
  confFile="${1}"
  api.PRINT "$(grep -m 1 Path= ${confFile} | sed 's|Path=||')"
}

getDate()
{
  confFile="${1}"
  api.PRINT "$(grep -m 1 DeletionDate= ${confFile} | sed 's|DeletionDate=||')"
}

add()
{
  checkFile "$1"
  if [ -e "${FILE}" ];
  then
    FILENAME="$(basename ${FILE})"
    DELFILE="${TRASHINFO}/${FILE}.trashinfo"
    DELPATH=$(readlink -f ${FILE})
    DELDATE=$(date +"%Y-%m-%dT%H:%M:%S")

    api.PRINT "[Trash Info]" > "${TRASHINFO}/${FILENAME}.trashinfo"
    api.PRINT "Path=${DELPATH}" >> "${TRASHINFO}/${FILENAME}.trashinfo"
    api.PRINT "DeletionDate=${DELDATE}" >> "${TRASHINFO}/${FILENAME}.trashinfo"
    mv ${FILE} ${TRASH}
    
    api.LOG "Moved ${FILE} to the trash!"
    exit 0
  else
    api.FAIL "File '${FILE}' doesn't exist!"
  fi
}

restore()
{
  checkFile "$1"

  FILEPATH="${TRASH}/${FILE}"
  FILEINFO="${TRASHINFO}/${FILE}.trashinfo"

  if [ -f "${FILEINFO}" ] && [ -e "${FILEPATH}" ];
  then
    RESTOREPATH="$(getPath ${FILEINFO})"
    
    mv "${FILEPATH}" "${RESTOREPATH}"
    rm -f "${FILEINFO}"

    api.LOG "Restored ${FILE} to ${RESTOREPATH}!"
    exit 0
  else
    api.FAIL "File ${FILE} is not in the trash!"
  fi
}

empty()
{
  local files=()

  # Create a list of all files in the trash, hidden and not hidden
  files=(`find ${TRASH} -maxdepth 1`)
  unset files[0]

  # Fail if there are no files in the trash
  [ ${#files[@]} -eq 0 ] && api.FAIL "There are no files in the trash!"

  # Remove all files from the trash
  for file in ${files[@]}
  do
    rm -rf $file
  done
  
  # Confirmation
  api.LOG "Emptied the trash!"
  exit 0
}

info()
{
  checkFile "$1"

  FILEINFO=$TRASHINFO/"${FILE}.trashinfo"
  
  if [ -e "${FILEINFO}" ];
  then
    cat "${FILEINFO}"
    exit 0
  else
    api.FAIL "File does not have metadata / doesn't exist!"
  fi
}

helpPrompt()
{
  api.PRINT 
  api.PRINT "Manage your trash bin"
  api.PRINT
  api.PRINT "Usage: `api.SCRIPTNAME` [command] <file>"
  api.PRINT "Example: `api.SCRIPTNAME` add <file>"
  api.PRINT
  api.PRINT "Commands:"
  api.PRINT "(a) add\t\t\tAdd a FILE to the trash"
  api.PRINT "(r) restore\t\tRestore a FILE from the trash"
  api.PRINT "(e) empty\t\tEmpty the trash bin"
  api.PRINT "(l) list\t\tList the contents of the trash bin"
  api.PRINT "(i) info\t\tGet a FILE's trash metadata"
  api.PRINT
  api.PRINT "Miscellaneous"
  api.PRINT "(h) help\t\tShow this prompt"
  api.PRINT "(v) version\t\tPrint the version of this script"
}

cmd=`api.LOWERCASE "${1}"`

case "${cmd}" in
  a | add )
    add "${2}"
    ;;
  r | restore)
    restore "${2}"
    ;;
  e | empty )
    empty
    ;;
  l | list )
    ls --color=auto -alvhF --group-directories-first $TRASH 
    exit 0
    ;;
  i | info )
    info "${2}"
    ;;
  v | version )
    api.VERSION
    ;;
  \? | h | help )
    helpPrompt
    ;;
  * )
  	[ -z "${cmd}" ] && helpPrompt || api.INVALID "${1}"
    ;;
esac
