#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: update
#   Version: 1.0
#
#   Usage: update
#
#   Description: Update all software on your
#	linux PC.
##############################################

PRINT()
{
	printf "%b\n" "$@"
}

PAUSE ()
{
    local p=""

    PRINT
    read -p "Press <ENTER> to continue..." p
    PRINT

    return 0
}

UPDATER()
{
	req="${1}"
	cmd="${2}"

	if [[ -x "$(command -v ${req})" ]]; then

		clear
		PRINT "Updating ${req}...\n"

		eval "${cmd}"

		PAUSE

	fi
}

UPDATER "flatpak" "flatpak update"
UPDATER "snap" "sudo snap refresh"
UPDATER "brew" "brew upgrade"
UPDATER "apt" "sudo apt update && sudo apt upgrade"
UPDATER "dnf" "sudo dnf update"
UPDATER "pacman" "sudo pacman -Syu"
UPDATER "yay" "yay -Syu"

clear
PRINT "Updates finished."
PAUSE
clear
