#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: winepurge
#	Version: 1.0
#
#	Usage: winepurge [command] [args]
#
#	Description:
#		Remove WINE and WINE applications from
#		your system
##############################################

version='1.0'
author='Nidia Achrys'

#######################################################################
#							Helper Functions						  #
#######################################################################
function SCRIPTNAME()
{
	echo "${0##*/}"
}

function PRINT()
{
	if [ -z "${1}" ]; then
		printf "\n"
	else
		printf "%b\n" "${1}"
	fi
}

function pause()
{
	read -p "Press ENTER to continue..." cmd
}

function lowercase()
{
	printf "${1}" | tr "[:upper:]" "[:lower:]"
}

function invalid()
{
	PRINT 
	PRINT "Invalid command \"${1}\". See \"`SCRIPTNAME` help\"."
	PRINT 
}

function emptycmd()
{
	PRINT 
	PRINT "You must specify a subcommand. See \"`SCRIPTNAME` help\"."
	PRINT 
}

function version()
{
	PRINT "`SCRIPTNAME` v${version}"
	PRINT "Copyright (C) `date +"%Y"` ${author}"
	PRINT "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
	PRINT "This is free software: you are free to change and redistribute it."
	PRINT "There is NO WARRANTY, to the extent permitted by law."
	PRINT
	PRINT "Written by ${author}."
}

#######################################################################
#								Core Code							  #
#######################################################################

pacman=$(command -v pacman)
apt=$(command -v apt)

if [[ $pcman ]];
then
	sudo pacman -Rnsv wine wine-gecko wine-mono winetricks wine-staging
elif [[ $apt ]];
then
	sudo apt remove wine-stable-amd wine-stable-i386 wine-stable
	sudo apt autoremove
fi

# Removes all leftover wine applications
cd $HOME
rm -rf .wine

# The lines below will remove all entries for any windows software
# installed with WINE from your application menu(s). Make sure to
# remove them using your menu editor as well.

rm -f $HOME/.config/menus/applications-merged/wine*
rm -rf $HOME/.local/share/applications/wine
rm -f $HOME/.local/share/desktop-directories/wine*
rm -f $HOME/.local/share/icons/????_*.{xpm,png}
rm -f $HOME/.local/share/icons/*-x-wine-*.{xpm,png}
