#!/bin/bash

#  ██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██╗  ██╗███████╗██╗     ██╗
#  ██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝██║     ██║
#  ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝███████╗███████║█████╗  ██║     ██║
#  ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗╚════██║██╔══██║██╔══╝  ██║     ██║
#  ██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║███████║██║  ██║███████╗███████╗███████╗
#  ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#

##############################################
# PRE-PROCESSING

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

DISABLE_ROOT || exit 1

##############################################
# HELP MENU BUILDER

VERSION "1.5"
DESCRIPTION "Create user scripts"
USAGE "[script name]"
##############################################
# FLAG HANDLING
ARGS=("$@")

for ((i = 0; i < ${#ARGS[@]}; i++)); do
	arg="${ARGS[i]}"

	case "$arg" in
	\? | -h | --help)
		HELP
		unset 'ARGS[i]'
		exit 0
		;;
	esac
done

##############################################
# MAIN LOGIC

SCRIPTS="${SCRIPTS:=$HOME/.local/bin}"
script="${ARGS[0]}"
scriptPath="${SCRIPTS}/${script}"

# Check to see if script name is provided
[[ -z "${script}" ]] && PRINT "You must specify a script name!" && exit 1

# Check to see if script exists
[[ ! -f "${scriptPath}" ]] &&
	PRINT "Script '${script}' doesn't exist!" && exit 1

# Edit the script
${EDITOR:=nano} "${scriptPath}" &&
	PRINT "$(SCRIPTNAME): Edited '${script}'." &&
	return 0

PRINT "Failed to edit '${script}'." &&
	return 1
