#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: appmgr
#   Version: 1.0
#
#   Usage:
#
#   Description:
#		Appmenu, App switcher, etc.
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

REQUIRE_CMD "rofi"

appmgr.menu() {
	rofi -show drun -scroll-method 1 -show-icons -columns 2 -disable-history -sorting-method 'fzf'
}

appmgr.switcher() {
	rofi -show window -window-icon -window-format "{c}    {t}"
}

appmgr.help() {
	appmgr.help.commands() {
		PRINT "Command|Arguments|Description"
		PRINT "menu||Application Menu"
		PRINT "switcher||Switch between running apps"
		PRINT "|||"
		PRINT "help||Show this help menu"
	}

	PRINT
	PRINT "Invoke common application management programs"
	PRINT
	PRINT "Usage:\t\tappmgr [command]"
	PRINT "Example:\tappmgr menu"
	PRINT
	appmgr.help.commands | column -t -s "|"
}

cmd="$(LOWERCASE "$1")"

case "${cmd}" in

menu) appmgr.menu ;;
switcher) appmgr.switcher ;;
help) appmgr.help ;;

*) [[ -z "${cmd}" ]] && appmgr.help && exit 0 ||
	PRINT "Invalid command '${cmd}'." && exit 1 ;;

esac
