#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: appmgr
#   Version: 1.0
#
#   Usage:
#
#   Description:
#		Appmenu, App switcher, etc.
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT
REQUIRE_CMD "rofi" || exit 1

####################################

function _menu() {
	SILENTRUN rofi -show drun -scroll-method 1 -show-icons -columns 2 -disable-history -sorting-method 'fzf'
}

function _switcher() {
	SILENTRUN rofi -show window -window-icon -window-format "{c}    {t}"
}

function _help() {
	PRINT "$(SCRIPTNAME) - Invoke common app management programs"
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) <flag> <args?>"
	PRINT "Example:\t$(SCRIPTNAME) --menu"
	PRINT
	{
		PRINT "-------------|------|---------------------"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------"
		PRINT "||"
		PRINT "--menu|n/a|Application Menu"
		PRINT "--switcher|n/a|Switch between running apps"
		PRINT "||"
		PRINT "-h, --help|n/a|Show this prompt"
	} | column -t -s'|'
}

# If no arguments are give, just show help prompt.
[[ $# -eq 0 ]] && _help && exit 0

# Iterate over all arguments and evaluate them
while test $# -gt 0; do

	case "$(LOWERCASE "${1}")" in

	-m | --menu)
		shift
		_menu
		exit $?
		;;

	-s | --switcher)
		shift
		_switcher
		exit $?
		;;

	\? | -h | --help)
		shift
		_help
		exit 0
		;;

	*) PRINT "$(SCRIPTNAME): Invalid argument '${1}'" && exit 1 ;;

	esac

done
