#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: bootableusb
#	Version: 1.0
# 
#	Usage: bootableusb <iso> /path/to/drive
# 
#	Description:
#		Create a bootable USB drive from an
#		ISO file 
##############################################

PRINT ()
{
	printf "%b\n" "${@}"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then

	PROGRAM_NAME="$(basename "$0")"

	PRINT "'${PROGRAM_NAME}' should not be run as root. Please try again as a normal user."
	exit 1
fi

bootableusb.write ()
{
	sudo dd bs=4M if="$1" of="$2" conv=fdatasync
}

bootableusb.help ()
{
	PRINT
	PRINT "Create a bootable USB drive"
	PRINT
	PRINT "Usage:\t\tbootableusb <iso> <drive>"
	PRINT "Example:\tbootableusb ubuntu.iso /dev/sdb"
	PRINT
}

if [[ "$1" = "--help" ]] || [[ $# -lt 1 ]]
then
	bootableusb.help
else
	bootableusb.write "$1" "$2"
fi
