#!/usr/bin/env python3

from pathlib import Path
from os import environ, geteuid, path
from sys import argv

# Check if running as root
if geteuid() == 0:
    print("This script should not be run as root. Please run as a normal user.")
    exit(1)


# Establish scripts folder
if not Path.exists(Path(environ['SCRIPTS'])):
    scriptsPath = Path(f"{environ['HOME']}{path.sep}.local{path.sep}bin")
else:
    scriptsPath = Path(environ['SCRIPTS'])

# Check if a filename was passed as an arg
try:
    argv[1]
except IndexError:
    print("You must provide a script name!")
    exit(1)

scriptName = argv[1]
scriptFile = Path(f"{scriptsPath}{path.sep}{scriptName}")

if not Path.exists(scriptFile):
    print(f"Script '{scriptName}' does not exist!")
    exit(1)

f = open(scriptFile, 'r')
f_contents = f.read()

print(f_contents)
