#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: correctGPGPermissions
#   Version: 1.0
#
#   Usage:
#
#   Description:
#		Correct the permissions for the gnupg directory
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

chown -R $(whoami) ~/.gnupg/

chmod 600 ~/.gnupg/*
chmod 700 ~/.gnupg
