#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: debinstall
#	Version: 1.0
#
#	Usage: debinstall [command] [args]
#
#	Description:
#		Change this
##############################################

PRINT()
{
	printf "%b\n" "${1}"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then

	PROGRAM_NAME="$(basename "$0")"

	PRINT "'${PROGRAM_NAME}' should not be run as root. Please try again as a normal user."
	exit 1
fi

[[ ! -x "$(which apt)" ]] && PRINT "This command requires 'apt'\!" && exit 1

if [[ $# -lt 1 ]]; then
	PRINT "Install debian packages\n"
	PRINT "Usage: debinstall <file>.deb"
	exit 0
fi

name="${1}"
name="${name##*/}"

if [[ ! "${name##*.}" == "deb" ]]; then

	PRINT "That is not a valid deb file!" && exit 1

fi

PRINT "\n\nInstalling '${name}'..."
sudo apt install "${1}" > /dev/null 2>&1

code=$?

[[ $code -eq 0 ]] && \
	PRINT "Installed '${name}'.\n" && exit 0 || \
	PRINT "Install failed.\n" && exit 1
