#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: debinstall
#	Version: 1.0
#
#	Usage: debinstall [command] [args]
#
#	Description:
#		Change this
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

CMD_EXISTS "apt" || PRINT "This command requires 'apt'\!" && exit 1

if [[ $# -lt 1 ]]; then
	PRINT "Install debian packages\n"
	PRINT "Usage: debinstall <file>.deb"
	exit 0
fi

name="${1}"
name="${name##*/}"

if [[ ! "${name##*.}" == "deb" ]]; then

	PRINT "That is not a valid deb file!" && exit 1

fi

PRINT "\n\nInstalling '${name}'..."
sudo apt install "${1}" >/dev/null 2>&1

code=$?

[[ $code -eq 0 ]] &&
	PRINT "Installed '${name}'.\n" && exit 0 ||
	PRINT "Install failed.\n" && exit 1
