#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: dice
#   Version: 1.0
#
#   Usage: dice <int[]>
#
#   Description:
#		Generate random number(s)
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT

####################################

RAW=1
ONELINE=1
NUMBERS=()
RESULTS=()

for arg in "$@"; do

	# if arg is not a int, look for '--raw' flag or continue; else add to NUMBERS array
	if (( $arg > 0 )); then

		NUMBERS+=("$arg")
		RESULTS+=("$(( $RANDOM % $arg + 1 ))")

	else

		[[ "$arg" == "--raw" ]] && RAW=0
		[[ "$arg" == "--oneline" ]] && ONELINE=0

	fi

done

# if the '--oneline' flag is used, print all results on a new line.
if [[ $ONELINE -eq 0 ]]; then

	for result in "${RESULTS[@]}"; do

		NPRINT "${result} "

	done

	PRINT

	exit 0

fi

# print the results on new lines; default format is 'd0: 0'; '--raw' prints format as '0'.
for (( i=0 ; i < ${#RESULTS[@]} ; i++ )); do

	[[ $RAW -eq 1 ]] && PRINT "d${NUMBERS[i]}: ${RESULTS[i]}" || PRINT "${RESULTS[i]}"

done

