#!/usr/bin/env python3

from random import randint
from sys import argv
from os import geteuid

# Variables
nums = []
minoutput = False


if __name__ == "__main__":

    # Check if running as root
    if geteuid() == 0:
        print("This script should not be run as root. Please run as a normal user.")
        exit(1)

    # Check argv length
        if len(argv) == 1:
            print("You must give arguments for this script!")
            exit(1)

    for arg in argv:

        if arg == '-r' or arg == '--raw':

            minoutput = True
            continue

        if arg.isdigit():

            nums.append(int(arg))
            continue

    for num in nums:

        result = randint(1, int(num))

        if minoutput is False:
            print(f"d{num}: {result}")
        else:
            print(f"{result}")
