#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: dice
#   Version: 1.0
#
#   Usage: dice <int[]>
#
#   Description:
#		Generate random number(s)
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT

####################################

RAW=1
ONELINE=1
NUMBERS=()
RESULTS=()

while test $# -gt 0; do

	case "$(LOWERCASE ${1})" in

		--raw ) shift; RAW=0 ;;
		--oneline ) shift; ONELINE=0 ;;
		* ) (( $1 > 0 )) && NUMBERS+=("$1") && RESULTS+=("$(( $RANDOM % $1 + 1 ))"); shift ;;

	esac
done

# if the '--oneline' flag is used, print all results on a new line.
[[ $ONELINE -eq 0 ]] && \
	(for result in "${RESULTS[@]}"; do NPRINT "${result} "; done) && PRINT && exit 0

# print the results on new lines; default format is 'd0: 0'; '--raw' prints format as '0'.
for (( i=0 ; i < ${#RESULTS[@]} ; i++ )); do

	[[ $RAW -eq 1 ]] && PRINT "d${NUMBERS[i]}: ${RESULTS[i]}" || PRINT "${RESULTS[i]}"

done

