#!/usr/bin/env bash

##############################################
#	Author: Roy Conn
#	Project: emojictl
#	Version: 1.0
#
#	Usage: emojictl [command] [args]
#
#	Description:
#		Install/uninstall Noto Color Emoji on Linux
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT
REQUIRE_CMD "wget" "unzip" "fc-cache" || exit 1

####################################

# Noto Emoji package link
EMOJIPKG="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"

CONFLINK="https://raw.githubusercontent.com/rmj1001/dotfiles/main/files/.config/fontconfig/conf.d"

# Fontconfig file links
FONTCONFIGS=(
	"${CONFLINK}/01-dejavu.conf"
	"${CONFLINK}/02-mozilla.conf"
	"${CONFLINK}/03-emoji.conf"
)

# Directories
CONFDIR=$HOME/.config/fontconfig/conf.d
NOTOPKG="$HOME/Downloads/$(basename ${EMOJIPKG})"
TEMP=$HOME/Downloads/temp
FONTS=$HOME/.fonts
FILE=${FONTS}/NotoColorEmoji.ttf

# cmd
cmd=""

function emojictl.prepare() {
	# Make the config directory and move to it
	[[ ! -d "${CONFDIR}" ]] && mkdir -p "${CONFDIR}"
	[[ ! -d "${FONTS}" ]] && mkdir -p "${FONTS}"
	[[ ! -d "${TEMP}" ]] || mkdir "${TEMP}"
	[[ -d "${TEMP}" ]] && rm -rf "${TEMP:?}/*"
	[[ -f "${FILE}" ]] && rm -rf "${FILE}"
	[[ -f "${NOTOPKG}" ]] && rm -f "${NOTOPKG}"
}

function emojictl.emojis.install() {
	clear

	# Make the config directory and move to it
	emojictl.prepare
	cd "$CONFDIR" || return 1

	# Download the fontconfig files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename "$file")
		rm -f "$name"
		wget "$file"
	done

	# Download noto emoji font
	cd "$TEMP" || return 1
	wget $EMOJIPKG

	# Install emojis
	unzip NotoColorEmoji-unhinted.zip
	mv NotoColorEmoji.ttf "$FONTS"
	fc-cache -fv
	rm -rf "$TEMP"

	# Post
	clear
	PRINT
	PRINT "Install finished."
	PRINT
	PAUSE
	clear
}

function emojictl.emojis.uninstall() {
	clear
	emojictl.prepare

	# Remove the font file
	rm -f "${FONTS}"/NotoColorEmoji.ttf

	# Remove the config files
	for file in "${FONTCONFIGS[@]}"; do
		name=$(basename "${file}")
		rm -f "${CONFDIR}/${name}"
	done

	# Reload the font cache
	fc-cache -fv

	# Post
	clear
	PRINT
	PRINT "Uninstall finished."
	PRINT
	PAUSE
	clear
}

function emojictl.help() {
	PRINT "$(SCRIPTNAME) - Manage system emojis"
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) <flag> <args?>"
	PRINT "Example:\t$(SCRIPTNAME) --help"
	PRINT
	{
		PRINT "-------------|------|---------------------"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------"
		PRINT "||"
		PRINT "-i, --install||Install emojis"
		PRINT "-u, --uninstall||Remove emojis"
		PRINT "||"
		PRINT "-h, --help|n/a|Show this prompt"
	} | column -t -s'|'
}

cmd="$(LOWERCASE "${1}")"

case "${cmd}" in

-i | --install)
	emojictl.emojis.install
	exit 0
	;;
-u | --uninstall)
	emojictl.emojis.uninstall
	exit 0
	;;
\? | -h | --help)
	emojictl.help
	exit 0
	;;
*)
	[ -z "${cmd}" ] && emojictl.help || PRINT "Invalid command '${1}'." && exit 1
	;;

esac
