#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: extract
#	Version: 1.0
#
#	Usage: extract [command] [args]
#
#	Description:
#		Extract any archive file
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

extract.valid() {
	if [[ ! -f "${1}" ]]; then
		PRINT "'${1}' is not a file."
		exit 1
	elif [[ -f "${1}" ]]; then
		return 0
	else
		PRINT "Unknown error"
		exit 1
	fi
}

extract.help() {
	PRINT "extract - Extract various archive files"
	PRINT
	PRINT "Supported file types:"
	PRINT "- tar.bz2"
	PRINT "- tar.gz"
	PRINT "- bz2"
	PRINT "- rar"
	PRINT "- gz"
	PRINT "- tar"
	PRINT "- tbz2"
	PRINT "- tgz"
	PRINT "- zip"
	PRINT "- Z"
	PRINT "- 7z"
	PRINT "- deb"
	PRINT "- tar.xz"
	PRINT "- tar.zst"
	PRINT
	return 0
}

case "${1}" in
*.tar.bz2)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xjf "${1}"
	;;
*.tar.gz)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xzf "${1}"
	;;
*.bz2)
	REQUIRE_CMD "bunzip"
	extract.valid "${1}"
	bunzip "${1}"
	;;
*.rar)
	REQUIRE_CMD "unrar"
	extract.valid "${1}"
	unrar x "${1}"
	;;
*.gz)
	REQUIRE_CMD "gunzip"
	extract.valid "${1}"
	gunzip "${1}"
	;;
*.tar)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xf "${1}"
	;;
*.tbz2)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xjf "${1}"
	;;
*.tgz)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xzf "${1}"
	;;
*.zip)
	REQUIRE_CMD "unzip"
	extract.valid "${1}"
	unzip "${1}"
	;;
*.Z)
	REQUIRE_CMD "uncompress"
	extract.valid "${1}"
	uncompress "${1}"
	;;
*.7z)
	REQUIRE_CMD "7z"
	extract.valid "${1}"
	7z x "${1}"
	;;
*.deb)
	REQUIRE_CMD "ar"
	extract.valid "${1}"
	ar x "${1}"
	;;
*.tar.xz)
	REQUIRE_CMD "tar"
	extract.valid "${1}"
	tar xf "${1}"
	;;
*.tar.zst)
	REQUIRE_CMD "unzstd"
	extract.valid "${1}"
	unzstd "${1}"
	;;
\? | h | help)
	extract.help
	;;
*)
	if [[ -z "${1}" ]]; then
		extract.help
	else
		PRINT "'${1}' cannot be extracted." && exit 1
	fi
	;;
esac
