#!/usr/bin/env bash

##############################################
#	Author: Roy Conn
#	Project: golive
#	Version: 1.0
#
#	Usage: golive [command] [args]
#
#	Description:
#		Force pulseaudio to use settings that allows
#		linux users to share audio via Discord's
#		golive feature
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT
REQUIRE_CMD "pactl"

####################################

golive.setup() {
	pactl list short modules | grep -q 'Virtual_Sink' && return

	if [ -z "$MIC_SOURCE" ]; then
		first_source=$(pactl list short sources | head -1 | awk '{print $1;}') # e.g. 0
		pactl list short sources
		read -r -p ">> Source (input) number to use [$first_source]: " user_source
		[ -z "$user_source" ] && user_source=$first_source
		MIC_SOURCE=$user_source
		PRINT
		first_sink=$(pactl list short sinks | head -1 | awk '{print $1;}') # e.g. 1
		pactl list short sinks
		read -r -p ">> Sink (output) number to use [$first_sink]: " user_sink
		[ -z "$user_sink" ] && user_sink=$first_sink
		OUTPUT_SINK=$user_sink
		PRINT
	fi

	pactl load-module module-null-sink sink_name=Virtual_Output sink_properties=device.description=Virtual_Output >/dev/null
	pactl load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink >/dev/null
	MIX_SOURCE=$(pactl list short sources | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 14

	pactl load-module module-loopback latency_msec=1 source="$MIC_SOURCE" sink=Virtual_Output >/dev/null
	pactl load-module module-loopback latency_msec=1 source="$MIX_SOURCE" sink=Virtual_Output >/dev/null
	MIX_LOOPBACK=$(pactl load-module module-loopback latency_msec=1 source="$MIX_SOURCE" sink="$OUTPUT_SINK")
}

golive.cleanup() {
	virtual_sink=$(pactl list short modules | grep 'Virtual_Sink' | awk '{print $1;}') # e.g. 30
	[ -z "$virtual_sink" ] && return
	read -r -p '>> Press enter to unload PulseAudio modules for the virtual mix...'

	[ ! -z "$MIX_LOOPBACK" ] && pactl unload-module "$MIX_LOOPBACK" || pactl unload-module module-loopback
	pactl list short modules | grep -E 'Virtual_(Sink|Output)' | awk '{print $1;}' | xargs -L1 pactl unload-module
}

golive.run() {
	golive.setup
	PRINT ">> Your virtual mix is currently active! Feel free to open e.g. 'pavucontrol' now."
	PRINT
	PRINT ">> For software that should have their audio included in the mix, move them"
	PRINT "   to the 'Virtual_Sink' under the 'Playback' tab."
	PRINT ">> For software that should capture the mixed audio, head to the 'Recording'"
	PRINT "   tab and make the software use 'Monitor of Virtual_Output' as their input."
	PRINT
	golive.cleanup
}

golive.help() {

	golive.help.commands() {
		PRINT "Commands|Arguments|Description"
		PRINT "(s) start||Start golive"
		PRINT "(h) help||Show this prompt"
	}

	PRINT
	PRINT "Enable/disable sound settings for discord golive"
	PRINT
	PRINT "Usage:\t\tgolive [command] <args?[]>"
	PRINT "Example:\tgolive start"
	PRINT
	golive.help.commands | column -t -s "|"
}

cmd="$(LOWERCASE "${1}")"

case "${cmd}" in
s | start)
	golive.run
	;;
\? | h | help)
	golive.help
	;;
*)
	if [ -z "${cmd}" ]; then
		golive.help
	else
		PRINT "Invalid command '${cmd}'" && exit 1
	fi
	;;
esac
