#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: lscripts.sh
#   Version: 1.0
#
#   Usage:
#
#   Description:
#		List all scripts in the ${SCRIPTS} directory
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

cd ${SCRIPTS}; find . -maxdepth 1 -type f -executable -exec echo "{}" \; | sed 's|\./||g'

