#!/usr/bin/env python3

from genericpath import isfile
from pathlib import Path
from sys import argv
from os import environ, geteuid, listdir, path

# Check if running as root
if geteuid() == 0:
    print("This script should not be run as root. Please run as a normal user.")
    exit(1)

# Establish scripts folder
if not Path.exists(Path(environ['SCRIPTS'])):
    scriptsPath = Path(f"{environ['HOME']}{path.sep}.local{path.sep}bin")
else:
    scriptsPath = Path(environ['SCRIPTS'])

scripts = listdir(scriptsPath)

scripts.sort()

for scriptName in scripts:
    if path.isfile(f"{scriptsPath}{path.sep}{scriptName}"):
        print(scriptName)

print()
