#!/usr/bin/env bash

##############################################
#	Author: Roy Conn
#	Project: matrix
#	Version: 1.0
#
#	Usage: matrix [command] [args]
#
#	Description:
#		Create a matrix screen
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT
TITLE "Matrix"

####################################

trap 'clear; exit' SIGTERM SIGINT

### Customization:
blue="\033[0;34m"
brightblue="\033[1;34m"
cyan="\033[0;36m"
brightcyan="\033[1;36m"
green="\033[0;32m"
brightgreen="\033[1;32m"
red="\033[0;31m"
brightred="\033[1;31m"
white="\033[1;37m"
black="\033[0;30m"
grey="\033[0;37m"
darkgrey="\033[1;30m"

colors=($green)

spacing=${1:-100}
scroll=${2:-0}
lines=$(expr $(tput lines) - 1 + $scroll)
cols=$(expr $(tput cols) / 2 - 1)

chars=(a b c d e f g h i j k l m n o p q r s t u v w x y z
	A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 ^)

count=${#chars[@]}
colorcount=${#colors[@]}

clear
tput cup 0 0

while :; do

	for i in $(eval echo {1..$lines}); do

		for i in $(eval echo {1..$cols}); do

			rand=$((RANDOM % spacing))

			case "$rand" in
			0) printf \
				"${colors[$RANDOM % $colorcount]}${chars[$RANDOM % $count]} " ;;
			1) printf "  " ;;
			*) printf "\033[2C" ;;
			esac

		done

		printf "\n"

	done

	tput cup 0 0

done
