#!/usr/bin/env bash

##############################################
# Author(s): RMCJ <rmichael1001@gmail.com>
# Project: minecraftctl
# Version: 1.0
#
# Usage: minecraftctl [command] [args]
#
# Description:
#	Manage minecraft installations
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT
REQUIRE_CMD "wget" "tar" "ar" || exit 1

####################################

desktopEntry="/usr/share/applications/minecraft-launcher.desktop"
downloadLink="https://launcher.mojang.com/download/Minecraft.deb"
binary="/usr/bin/minecraft-launcher"
desktopEntry="/usr/share/applications/minecraft.desktop"

function minecraftctl.install() {
	# Clear Screen
	clear

	# Variables
	local link="${downloadLink}"
	local dentry="${desktopEntry}"

	# Download
	cd "${HOME}/Downloads" || return 1

	# If deb file exists, delete and download new one, otherwise just download
	[[ -f "Minecraft.deb" ]] && clear && rm -f ./Minecraft.deb
	wget "${link}"

	PRINT "Installing Minecraft..."

	# Install the deb file
	sudo ar xvf Minecraft.deb
	sudo tar xvf data.tar.xz -C /
	sudo rm control.tar.gz data.tar.xz debian-binary

	# Desktop Entry
	entryText="Exec=env JAVA_HOME=/usr/lib64/openjdk-8 ${binary}"

	# Create the desktop entry
	PRINT "${entryText}" | sudo tee -a "${dentry}"
	PRINT "Icon=/usr/share/icons/hicolor/symbolic/apps/minecraft-launcher.svg" | sudo tee -a "${dentry}"
	PAUSE

	# Confirmation
	clear
	PRINT "Installation finished."
	PRINT
	PAUSE
	clear
}

function minecraftctl.remove() {
	# Clear screen
	clear

	local launcherExisted=0 # Tracks existence of launcher directories
	local filesExisted=0    # Tracks existence of any files from minecraftctl.

	# Remove launcher files
	[[ -e "${binary}" ]] && launcherExisted=1 && sudo rm -rf ${binary} && sleep 1.5
	[[ -e "${desktopEntry}" ]] && launcherExisted=1 && sudo rm -rf ${desktopEntry} &&
		PRINT "Removed desktop entry." && sleep 1.5

	[[ ${launcherExisted} -eq 1 ]] && filesExisted=1 && PRINT "Removed launcher."
	[[ ${filesExisted} -eq 1 ]] && PRINT "Uninstallation finished."
	[[ ${filesExisted} -ne 1 ]] && PRINT "Minecraft is not installed."

	# Confirmation
	PAUSE
	clear
}

function minecraftctl.help() {
	PRINT "$(SCRIPTNAME) - Manage your minecraft installation"
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) <flag> <args?>"
	PRINT "Example:\t$(SCRIPTNAME) --help"
	PRINT
	{
		PRINT "-------------|------|---------------------"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------"
		PRINT "||"
		PRINT "-i, --install||Install minecraft"
		PRINT "-r, --remove||Uninstall minecraft"
		PRINT "-u, --update||Update minecraft"
		PRINT "||"
		PRINT "-h, --help|n/a|Show this prompt"
	} | column -t -s'|'
}

[[ $# -eq 0 ]] && minecraftctl.help && exit 0

case "$(LOWERCASE "${1}")" in
-i | --install)
	minecraftctl.install
	;;
-r | --remove)
	minecraftctl.remove
	;;
-u | --update)
	minecraftctl.remove && minecraftctl.install
	;;
\? | -h | --help)
	minecraftctl.help
	;;
*)
	PRINT "'${1}' is an invalid subcommand!"
	;;
esac
