#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: mp3dl
#	Version: 1.0
#
#	Usage: mp3dl [command] [args]
#
#	Description:
#		Download youtube videos and convert
#		them to mp3 files
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

REQUIRE_CMD "youtube-dl"

mp3dl.download() {
	# Preparations
	DIR=$HOME/Downloads/Music
	[[ -d "$DIR" ]] || mkdir "$DIR"

	cd "$DIR" || exit

	# Download
	youtube-dl \
		--prefer-ffmpeg \
		--add-metadata \
		--output '%(title)s.%(ext)s' \
		--extract-audio \
		--audio-format mp3 "${@}"
}

if [[ $# -lt 1 ]]; then

	# Help message
	PRINT "mp3dl - Download youtube videos"
	PRINT "\nUsage: mp3dl <video[]>"

else

	mp3dl.download "$@"

fi
