#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: pactools
#   Version: 1.0
#
#   Usage: [flags]
#
#   Description:
#		Browse installed pacman packages
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

_browse() {
	trap 'exit 0' SIGINT SIGHUP

	[[ ! -x "$(which pacman)" ]] && PRINT "This can only be run on Arch linux!" && exit 1

	pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'

	exit 0
}

_refresh_mirrors() {
	[[ -x "$(which reflector)" ]] || exit 1

	sudo reflector --latest 100 --protocol https --sort rate --verbose --save /etc/pacman.d/mirrorlist

	exit 0
}

_list_orphans() {
	pacman -Qtdq
}

_remove_orphans() {
	pacman -Qtdq | sudo pacman -Rns -
}

_help() {

	_help.commands() {
		PRINT "Command|Arguments|Description"
		PRINT "browse||Browse installed packages"
		PRINT "refresh-mirrors||Refresh your mirror list"
		PRINT "list-orphans||List dependencies no longer required by any packages"
		PRINT "remove-orphans||Remove orphans and their config files"
	}

	PRINT
	PRINT "pactools - Various pacman tools"
	PRINT
	PRINT "Usage:\t\tpactools [command] <args?[]>"
	PRINT "Example:\tpactools refresh-mirrors"
	PRINT
	_help.commands | column -t -s '|'
	PRINT
}

case "$(LOWERCASE "$1")" in

browse) _browse ;;

refresh-mirrors) _refresh_mirrors ;;

list-orphans) _list_orphans ;;

remove-orphans) _remove_orphans ;;

help) _help ;;

*)
	[[ -z "$1" ]] && _help && exit 0
	PRINT "Invalid command '$1'!" && exit 1
	;;

esac
