#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: pactools
#   Version: 1.0
#
#   Usage: [flags]
#
#   Description:
#	Browse installed pacman packages
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT

####################################

_browse() {
	trap 'exit 0' SIGINT SIGHUP

	REQUIRE_CMD "pacman" || return 1

	pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

_refresh_mirrors() {
	REQUIRE_CMD "reflector" || return 1

	sudo reflector --latest 100 --protocol https --sort rate --verbose --save /etc/pacman.d/mirrorlist
}

_list_orphans() {
	pacman -Qtdq
}

_remove_orphans() {
	pacman -Qtdq | sudo pacman -Rns -
}

_help() {

	_help.commands() {
		PRINT "Command|Arguments|Description"
		PRINT "-b, --browse||Browse installed packages"
		PRINT "-u, --update-mirrors||Update your mirror list"
		PRINT "-l, --list-orphans||List dependencies no longer required by any packages"
		PRINT "-r, --remove-orphans||Remove orphans and their config files"
	}

	PRINT
	PRINT "pactools - Various pacman tools"
	PRINT
	PRINT "Usage:\t\tpactools [command] <args?[]>"
	PRINT "Example:\tpactools refresh-mirrors"
	PRINT
	_help.commands | column -t -s '|'
	PRINT
}

case "$(LOWERCASE "$1")" in

-b | --browse) _browse ;;

-u | --update-mirrors) _refresh_mirrors ;;

-l | --list-orphans) _list_orphans ;;

-r | --remove-orphans) _remove_orphans ;;

\? | -h | --help) _help ;;

*)
	[[ -z "$1" ]] && _help && exit 0
	PRINT "Invalid command '$1'!" && exit 1
	;;

esac
