#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: lutris
#   Version: 1.0
#
#   Usage:
#
#   Description:
#
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS}"/00-api.sh

####################################

DISABLE_ROOT

ppas=(
	"ppa:lutris-team/lutris"
)

packages=(
	"lutris"
	"steam-installer"
	"meson"
	"libsystemd-dev"
	"pkg-config"
	"ninja-build"
	"git"
	"libdbus-1-dev"
	"libinih-dev"
)

gamemodeVersion="1.6.1"

_install() {
	# Lutris Repo

	for ppa in "${ppas[@]}"; do

		sudo add-apt-repository -y -n "${ppa}"

	done

	sudo apt update

	sudo apt install "${packages[@]}"

	# Gamemode
	cd $HOME/Downloads
	[[ -d "$HOME/Downloads/gamemode" ]] || git clone https://github.com/FeralInteractive/gamemode.git
	cd gamemode

	git checkout "${gamemodeVersion}"
	./bootstrap.sh
}

_uninstall() {

	sudo apt remove "${packages[@]}"

	for ppa in "${ppas[@]}"; do

		sudo add-apt-repository -y -n -r "${ppa}"

	done

	sudo apt update
}

_help() {
	_help.commands() {
		PRINT "Commands|Arguments|Description"
		PRINT "(i) install||Install gaming software on Ubuntu"
		PRINT "(u) uninstall||Remove gaming software from Ubuntu"
		PRINT "(h) help||Show this help menu"
	}

	PRINT
	PRINT "Install/Uninstall gaming software on Ubuntu"
	PRINT
	PRINT "Usage:\t\tubuntu_gaming <command>"
	PRINT "Example:\tubuntu_gaming install"
	PRINT
	_help.commands | column -t -s "|"
}

case "$(LOWERCASE "${1}")" in

i | install) _install ;;
u | uninstall) _uninstall ;;
\? | h | help) _help ;;
*)
	[[ -z "${1}" ]] && _help && exit 0
	PRINT "Invalid command '$1'." && return 1
	;;
esac
