#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: update
#   Version: 1.0
#
#   Usage: update
#
#   Description: Update all software on your
#	linux PC.
##############################################

PRINT()
{
	printf "%b\n" "$@"
}

PAUSE ()
{
    PRINT
    read -r -p "Press <ENTER> to continue..."

    PRINT

    return 0
}

UPDATER()
{
	req="${1}"
	cmd="${2}"

	if [[ -x "$(command -v "${req}")" ]]; then

		clear

		read -p "Update "${req}"? (Y/n) " confirmation

		if [[ ${confirmation} =~ [yY][eE]?[sS]? ]] \
			|| [[ -z "${confirmation}" ]]; then

			PRINT "Updating ${req}...\n"
			eval "${cmd}"
		else
			PRINT "Skipped updating ${req}...\n"
		fi

		PAUSE

	fi
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then

	PROGRAM_NAME="$(basename "$0")"

	PRINT "'${PROGRAM_NAME}' should not be run as root. Please try again as a normal user."
	exit 1
fi

UPDATER "flatpak" "flatpak update"
UPDATER "snap" "sudo snap refresh"
UPDATER "brew" "brew upgrade"
UPDATER "apt" "sudo apt update && sudo apt upgrade"
UPDATER "dnf" "sudo dnf update"
UPDATER "pacman" "sudo pacman -Syu --noconfirm"
UPDATER "yay" "yay -Sua --noconfirm"
UPDATER "paru" "paru -Sua --noconfirm"

clear
PRINT "Updates finished."
PAUSE
clear
