#!/usr/bin/env bash

##############################################
#	Author: Nidia Achrys
#	Project: volume
#	Version: 1.0
#
#	Usage: volume [command] [args]
#
#	Description:
#		Control volume from the terminal
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessor flags
DISABLE_ROOT

####################################

_up() {
	percent=${1:-15}
	amixer sset Master "${percent}%+" >/dev/null 2>&1
}

_down() {
	percent=${1:-15}
	amixer sset Master "${percent}%-" >/dev/null 2>&1
}

_mute() {
	amixer sset Master toggle >/dev/null 2>&1
}

_view() {
	local volume

	volume="$(amixer sget Master | grep 'Front Left' | grep '%' | sed -e 's|.* Playback [0-9]* ||g' -e 's|\[on\]||g' -re 's|[^0-9]||g')%"

	PRINT "${volume}"
}

_help() {

	_commands() {
		PRINT "Commands|Arguments|Description"
		PRINT "(u) up|[%]|Increase volume"
		PRINT "(d) down|[%]|Decrease volume"
		PRINT "(m) mute||Toggle mute"
		PRINT "(v) view||View the current volume"
		PRINT "(h) help||Show this help menu"
	}

	PRINT
	PRINT "Control volume from the terminal"
	PRINT
	PRINT "Usage:   volume [command] <args?[]>"
	PRINT "Example: volume up 5"
	PRINT
	_commands | column -t -s "|"
	return 0
}

cmd="$(printf '%b' "${1}" | tr '[:upper:]' '[:lower:]')"

case "${cmd}" in

	u | up)
		_up "$2"
		;;

	d | down)
		_down "$2"
		;;

	m | mute)
		_mute
		;;

	v | view)
		_view
		;;

	\? | h | help)
		_help
		;;

	*)
		[ -z "${1}" ] && _help || PRINT "Invalid command '${1}'!" && exit 1
		;;
esac
