#!/usr/bin/env bash

##############################################
#   Author: Roy Conn
#   Project: volume
#   Version: 1.0
#
#   Usage: volume [flag] [args]...
#
#   Description:
#		Control your system's volume
##############################################

# shellcheck disable=SC1091
source "${SCRIPTS:=$HOME/.local/bin}"/00-api.sh

# Preprocessing flags
DISABLE_ROOT

####################################

_help() {
	_flags() {
		PRINT "-------------|------|---------------------|"
		PRINT "Flag|Args|Description"
		PRINT "-------------|------|---------------------|"
		PRINT "|||"
		PRINT "-u, --up|%|Turn up volume"
		PRINT "-d, --down|%|Turn down volume|"
		PRINT "-m, --mute|n/a|Turn off volume|"
		PRINT "-v, --view|n/a|View current volume|"
		PRINT "|||"
		PRINT "-h, --help|n/a|Show this prompt"
	}

	PRINT "$(SCRIPTNAME) - description"
	PRINT
	PRINT "Usage:\t\t$(SCRIPTNAME) <flag> <args?>"
	PRINT "Example:\t$(SCRIPTNAME) --help"
	PRINT
	_flags | column -t -s'|'
}

_up() {
	percent=${1:-15}
	SILENTRUN amixer sset Master "${percent}%+"
}

_down() {
	percent=${1:-15}
	SILENTRUN amixer sset Master "${percent}%-"
}

_mute() {
	SILENTRUN amixer sset Master toggle
}

_view() {
	local volume

	volume="$(amixer sget Master | grep 'Front Left' | grep '%' | sed -e 's|.* Playback [0-9]* ||g' -e 's|\[on\]||g' -re 's|[^0-9]||g')%"

	PRINT "${volume}"
}

# If no arguments are give, just show help prompt.
[[ $# -eq 0 ]] && _help && exit 0

# Iterate over all arguments and evaluate them
while test $# -gt 0; do

	case "$(LOWERCASE "${1}")" in

	-u | --up)
		shift
		_up "${1}"
		shift
		;;

	-d | --down)
		shift
		_down "${1}"
		shift
		;;

	-m | --mute)
		shift
		_mute
		;;

	-v | --view)
		shift
		_view
		;;

	\? | -h | --help)
		shift
		_help
		exit 0
		;;

	*) PRINT "$(SCRIPTNAME): Invalid argument '${1}'" && exit 1 ;;

	esac

done
